// libraries/react-components/frontend/angular/src/app/features/admin/error-log/app-errors-tab.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { COMMON_COLUMNS, orDash } from './error-log-columns';
import { ErrorLogTable } from './error-log-table';
import { ErrorLogToolbar } from './error-log-toolbar';
import { channelView } from './channel-view';

import type { ErrorLogColumn } from './error-log-columns';
import type { ErrorLogEntry } from '../../../core/errors/error-log.types';

/** `context.kind` is what each capture point stamps; surface it as the source. */
function sourceOf(entry: ErrorLogEntry): string {
  const kind = entry.context?.['kind'];
  return typeof kind === 'string' ? kind : 'app';
}

const COLUMNS: ErrorLogColumn[] = [
  ...COMMON_COLUMNS,
  { key: 'source', label: 'Source', kind: 'mono', value: sourceOf },
  {
    key: 'file',
    label: 'File',
    kind: 'mono',
    value: (e) => `${e.fileName}${e.lineNumber == null ? '' : `:${String(e.lineNumber)}`}`,
  },
  { key: 'route', label: 'Route', kind: 'mono', value: (e) => orDash(e.route) },
  { key: 'error', label: 'Error', kind: 'mono', value: (e) => e.error },
  {
    key: 'description',
    label: 'Description',
    value: (e) => e.errorDescription,
    tooltip: (e) =>
      e.breadcrumbs?.length
        ? `trail: ${e.breadcrumbs.map((b) => `${b.category}:${b.message}`).join(' > ')}`
        : JSON.stringify(e.context ?? {}),
  },
];

/**
 * Everything that is not an HTTP failure: uncaught exceptions, rejected
 * promises, console errors, guard denials, form validation blocks and
 * component-level failures.
 *
 * The `Source` column is what makes this tab usable — one channel holding six
 * kinds of event is only navigable if each entry says which kind it is.
 */
@Component({
  selector: 'app-app-errors-tab',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ErrorLogTable, ErrorLogToolbar],
  template: `
    <p class="tab__lede">
      Application-level events: uncaught exceptions, unhandled rejections, console errors, denied
      route access and blocked form submissions, each tagged with the capture point that recorded
      it.
    </p>

    <app-error-log-toolbar [view]="view" channelLabel="application" />

    <app-error-log-table
      [entries]="view.rows()"
      [columns]="columns"
      [countByFingerprint]="view.countByFingerprint()"
      caption="Application errors, newest first"
      emptyMessage="No application errors recorded."
    />
  `,
  styles: `
    :host { display: block; }
    .tab__lede {
      margin: 0 0 12px;
      max-width: 90ch;
      color: var(--mat-sys-on-surface-variant);
      font: var(--mat-sys-body-medium);
    }
  `,
})
export class AppErrorsTab {
  protected readonly view = channelView('app');
  protected readonly columns = COLUMNS;
}

// libraries/archive/react-components/frontend/react/src/components/errors/tabs/AppErrorsTab.tsx
import Stack from '@mui/material/Stack';
import Tooltip from '@mui/material/Tooltip';
import Typography from '@mui/material/Typography';
import { useMemo, useState } from 'react';

import { commonColumns, type ErrorLogColumn } from '../errorLogColumns';
import { ErrorLogTable } from '../ErrorLogTable';
import { ErrorLogToolbar } from '../ErrorLogToolbar';
import { Mono } from '../Mono';
import { useErrorLog } from '../useErrorLog';

import type { ErrorLogEntry } from '@/types/errorLog';

/** `context.kind` is what each capture point stamps; surface it as the source. */
function sourceOf(entry: ErrorLogEntry): string {
  const kind = entry.context?.kind;
  return typeof kind === 'string' ? kind : 'app';
}

const columns: ErrorLogColumn[] = [
  ...commonColumns,
  {
    key: 'source',
    label: 'Source',
    render: (e) => <Mono>{sourceOf(e)}</Mono>,
  },
  {
    key: 'file',
    label: 'File',
    render: (e) => (
      <Mono>
        {e.fileName}
        {e.lineNumber != null ? `:${String(e.lineNumber)}` : ''}
      </Mono>
    ),
  },
  {
    key: 'route',
    label: 'Route',
    render: (e) => <Mono>{e.route ?? '—'}</Mono>,
  },
  {
    key: 'error',
    label: 'Error',
    render: (e) => <Mono>{e.error}</Mono>,
  },
  {
    key: 'description',
    label: 'Description',
    render: (e) => (
      <Tooltip
        title={
          e.breadcrumbs?.length
            ? `trail: ${e.breadcrumbs.map((b) => `${b.category}:${b.message}`).join(' > ')}`
            : JSON.stringify(e.context ?? {})
        }
      >
        <span>{e.errorDescription}</span>
      </Tooltip>
    ),
  },
];

/**
 * Everything the running app produced that is not a request failure: render
 * crashes caught by the error boundary, route/loader failures, uncaught runtime
 * errors, unhandled promise rejections, failed chunk loads, mirrored
 * `console.error` output, and connectivity loss.
 */
export function AppErrorsTab() {
  const log = useErrorLog('app');
  const [grouped, setGrouped] = useState(true);

  const rows = useMemo(
    () => (grouped ? log.grouped.map((group) => group.entry) : log.filtered),
    [grouped, log.grouped, log.filtered],
  );
  const counts = useMemo(
    () => new Map(log.grouped.map((group) => [group.entry.fingerprint, group.count])),
    [log.grouped],
  );

  return (
    <Stack spacing={1}>
      <Typography variant="body2" color="text.secondary">
        Render crashes, route and loader failures, uncaught errors, unhandled rejections, chunk-load
        failures, mirrored <code>console.error</code> output and offline events. Grouped by
        fingerprint by default, so one recurring fault reads as one row.
      </Typography>

      <ErrorLogToolbar
        entries={log.entries}
        filtered={log.filtered}
        counts={log.counts}
        level={log.level}
        onLevelChange={log.setLevel}
        search={log.search}
        onSearchChange={log.setSearch}
        grouped={grouped}
        onGroupedChange={setGrouped}
        onRefresh={log.refresh}
        onClear={log.clearChannel}
        channelLabel="app"
      />

      <ErrorLogTable
        entries={rows}
        columns={columns}
        countByFingerprint={grouped ? counts : undefined}
        emptyMessage="No app errors recorded. Trigger a render error or navigate to an unknown route to generate one."
      />
    </Stack>
  );
}
