// libraries/react-components/frontend/angular/src/app/shared/breadcrumbs/app-breadcrumbs.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { MatIconModule } from '@angular/material/icon';
import { NavigationEnd, Router, RouterLink } from '@angular/router';
import { filter, map, startWith } from 'rxjs';

import { buildBreadcrumbs } from '../../layout/breadcrumbs';

/**
 * The breadcrumb trail for the current URL.
 *
 * Renders nothing at the top of a hierarchy: a single crumb saying where you
 * already are is noise, and an empty `<nav>` is worse than no `<nav>`.
 *
 * The trail comes from `buildBreadcrumbs`, which reads the same nav arrays the
 * sidebars render — so this never carries its own copy of a page's label.
 */
@Component({
  selector: 'app-breadcrumbs',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatIconModule, RouterLink],
  template: `
    @if (crumbs().length > 1) {
      <nav aria-label="Breadcrumb">
        <ol class="crumbs">
          @for (crumb of crumbs(); track $index) {
            <li class="crumbs__item">
              @if (crumb.path) {
                <a class="crumbs__link" [routerLink]="crumb.path">
                  @if (crumb.path === '/') {
                    <mat-icon class="crumbs__icon">home</mat-icon>
                  }
                  {{ crumb.label }}
                </a>
              } @else {
                <!--
                  The current page: text, not a link. "aria-current" is what
                  tells a screen reader which crumb it is standing on.
                -->
                <span class="crumbs__current" aria-current="page">{{ crumb.label }}</span>
              }

              @if (!$last) {
                <mat-icon class="crumbs__sep" aria-hidden="true">navigate_next</mat-icon>
              }
            </li>
          }
        </ol>
      </nav>
    }
  `,
  styles: `
    :host { display: block; margin-bottom: 16px; }
    .crumbs {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 2px;
      list-style: none;
      margin: 0;
      padding: 0;
    }
    .crumbs__item { display: inline-flex; align-items: center; }
    .crumbs__link,
    .crumbs__current {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      font: var(--mat-sys-body-medium);
    }
    .crumbs__link {
      color: var(--mat-sys-on-surface-variant);
      text-decoration: none;
      border-radius: 4px;
      padding: 2px 4px;
    }
    .crumbs__link:hover { text-decoration: underline; }
    .crumbs__link:focus-visible { outline: 2px solid var(--mat-sys-primary); outline-offset: 1px; }
    .crumbs__current { font-weight: 600; padding: 2px 4px; }
    .crumbs__icon, .crumbs__sep {
      font-size: 18px;
      width: 18px;
      height: 18px;
      color: var(--mat-sys-on-surface-variant);
    }
  `,
})
export class AppBreadcrumbs {
  private readonly router = inject(Router);

  /**
   * The router's URL as a signal.
   *
   * `Router.events` is one of the few Angular APIs that is still an Observable,
   * so it is converted here at the boundary. `startWith` covers the first
   * render, which happens after the navigation that caused it.
   */
  private readonly url = toSignal(
    this.router.events.pipe(
      filter((event) => event instanceof NavigationEnd),
      map(() => this.router.url),
      startWith(this.router.url),
    ),
    { initialValue: this.router.url },
  );

  protected readonly crumbs = computed(() => {
    const url = this.url();
    const queryIndex = url.indexOf('?');
    const pathname = queryIndex === -1 ? url : url.slice(0, queryIndex);
    const search = queryIndex === -1 ? '' : url.slice(queryIndex);
    // The router keeps the URL encoded; `?doc=auth%2Fauth-service.md` has to
    // come back as a path before it can be split into crumbs.
    return buildBreadcrumbs(decodeURIComponent(pathname), search);
  });
}

// libraries/react-components/frontend/react/src/components/AppBreadcrumbs/AppBreadcrumbs.tsx
import HomeIcon from '@mui/icons-material/Home';
import NavigateNextIcon from '@mui/icons-material/NavigateNext';
import Box from '@mui/material/Box';
import Breadcrumbs from '@mui/material/Breadcrumbs';
import Link from '@mui/material/Link';
import Typography from '@mui/material/Typography';
import { memo } from 'react';
import { Link as RouterLink, useLocation } from 'react-router-dom';

import { buildBreadcrumbs } from '@/routes/breadcrumbs';

/**
 * The breadcrumb trail for the current location.
 *
 * Renders nothing at the top of a hierarchy: a single crumb saying where you
 * already are is noise, and an empty `<nav>` is worse than no `<nav>`.
 *
 * The trail comes from `buildBreadcrumbs`, which reads the same nav arrays the
 * sidebars render — so this never carries its own copy of a page's label.
 */
export const AppBreadcrumbs = memo(function AppBreadcrumbs() {
  const location = useLocation();
  const crumbs = buildBreadcrumbs(location.pathname, location.search);

  if (crumbs.length < 2) return null;

  return (
    <Box sx={{ mb: 2 }}>
      <Breadcrumbs
        aria-label="Breadcrumb"
        separator={<NavigateNextIcon fontSize="small" />}
        sx={{ '& .MuiBreadcrumbs-separator': { mx: 0.5 } }}
      >
        {crumbs.map((crumb, index) =>
          crumb.to === undefined ? (
            // The current page: text, not a link. `aria-current` is what tells a
            // screen reader which crumb it is standing on.
            <Typography
              key={`${crumb.label}-${String(index)}`}
              color="text.primary"
              variant="body2"
              fontWeight={600}
              aria-current="page"
            >
              {crumb.label}
            </Typography>
          ) : (
            <Link
              key={`${crumb.label}-${String(index)}`}
              component={RouterLink}
              to={crumb.to}
              underline="hover"
              color="inherit"
              variant="body2"
              sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}
            >
              {crumb.to === '/' && <HomeIcon fontSize="inherit" />}
              {crumb.label}
            </Link>
          ),
        )}
      </Breadcrumbs>
    </Box>
  );
});
