// libraries/react-components/frontend/react/src/features/public/AboutPage.tsx
import CardContent from '@mui/material/CardContent';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';

import { glassAccents } from '@/components/glass/glassAccents';
import { GlassCard } from '@/components/glass/GlassCard';
import { PageContainer } from '@/components/glass/PageContainer';

const pillars = [
  {
    title: 'Component reuse',
    body: 'A typed component library — cards, grids, editors and theme primitives shared across every page.',
    accent: glassAccents.violet,
  },
  {
    title: 'Clean routing',
    body: 'A public marketing shell and a protected admin console, each with its own chrome and error boundaries.',
    accent: glassAccents.teal,
  },
  {
    title: 'Reliable data',
    body: 'Query-cached fetching with optimistic and pessimistic update strategies and graceful error states.',
    accent: glassAccents.amber,
  },
];

/**
 * About page, ported from the CodeGen project and adapted to this app's
 * theme system — mission statement + pillar cards. The team moved to its own
 * page (/team).
 */
export function AboutPage() {
  return (
    <PageContainer
      title="About Idol-Promo"
      subtitle="A production-shaped reference app proving that maintainable code and a beautiful, modern aesthetic are not mutually exclusive."
    >
      <Grid container spacing={3} sx={{ mb: 5, alignItems: 'stretch' }}>
        {pillars.map((pillar) => (
          <Grid key={pillar.title} size={{ xs: 12, md: 4 }}>
            <GlassCard interactive accent={pillar.accent} sx={{ height: '100%' }}>
              <CardContent>
                <Typography variant="h6" sx={{ fontWeight: 700 }} gutterBottom>
                  {pillar.title}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  {pillar.body}
                </Typography>
              </CardContent>
            </GlassCard>
          </Grid>
        ))}
      </Grid>

      <GlassCard sx={{ p: { xs: 3, md: 5 } }}>
        <Typography variant="h5" sx={{ fontWeight: 700 }} gutterBottom>
          Our mission
        </Typography>
        <Typography variant="body1" color="text.secondary" sx={{ maxWidth: 720 }}>
          We build production-friendly interfaces with strong component reuse, clean routing and
          reliable data fetching — proving that maintainable code and a beautiful, modern aesthetic
          are not mutually exclusive.
        </Typography>
      </GlassCard>
    </PageContainer>
  );
}

// libraries/react-components/frontend/angular/src/app/features/public/about-page.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';

import { AccentCard } from '../../shared/accent-card/accent-card';
import { PageContainer } from '../../shared/page-container/page-container';

import type { AccentName } from '../../shared/accent-card/accent-card';

interface Pillar {
  readonly title: string;
  readonly body: string;
  readonly accent: AccentName;
}

const PILLARS: readonly Pillar[] = [
  {
    title: 'Component reuse',
    body: 'A typed component library — cards, grids, editors and theme primitives shared across every page.',
    accent: 'violet',
  },
  {
    title: 'Clean routing',
    body: 'A public marketing shell and a guarded admin console, each with its own chrome and error handling.',
    accent: 'teal',
  },
  {
    title: 'Reliable data',
    body: 'Cached fetching over httpResource, with explicit invalidation and graceful error states.',
    accent: 'amber',
  },
];

/** About page: mission statement and the three pillars, ported from React. */
@Component({
  selector: 'app-about-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [AccentCard, MatCardModule, PageContainer],
  template: `
    <app-page-container
      title="About Idol-Promo"
      subtitle="A production-shaped reference app proving that maintainable code and a polished, modern aesthetic are not mutually exclusive."
    >
      <div class="about__grid">
        @for (pillar of pillars; track pillar.title) {
          <app-accent-card interactive [accent]="pillar.accent">
            <mat-card-content>
              <h2 class="about__pillar-title">{{ pillar.title }}</h2>
              <p class="about__body">{{ pillar.body }}</p>
            </mat-card-content>
          </app-accent-card>
        }
      </div>

      <app-accent-card>
        <mat-card-content class="about__mission">
          <h2 class="about__mission-title">Our mission</h2>
          <p class="about__body">
            We build production-friendly interfaces with strong component reuse, clean routing and
            reliable data fetching — proving that maintainable code and a beautiful, modern
            aesthetic are not mutually exclusive.
          </p>
        </mat-card-content>
      </app-accent-card>
    </app-page-container>
  `,
  styles: `
    .about__grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      gap: 24px;
      margin-bottom: 40px;
    }
    .about__pillar-title {
      margin: 0 0 8px;
      font: var(--mat-sys-title-medium);
      font-weight: 700;
    }
    .about__mission { padding: 16px 8px; }
    .about__mission-title {
      margin: 0 0 8px;
      font: var(--mat-sys-headline-small);
      font-weight: 700;
    }
    .about__body {
      margin: 0;
      max-width: 72ch;
      color: var(--mat-sys-on-surface-variant);
    }
  `,
})
export class AboutPage {
  protected readonly pillars = PILLARS;
}
