// libraries/react-components/frontend/react/src/components/errors/tabs/TestErrorsTab.tsx
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import RefreshIcon from '@mui/icons-material/Refresh';
import Alert from '@mui/material/Alert';
import AlertTitle from '@mui/material/AlertTitle';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import CircularProgress from '@mui/material/CircularProgress';
import Paper from '@mui/material/Paper';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { queryKeys } from '@/api/queryKeys';
import { usePermission } from '@/auth/usePermission';
import { canRunTests, runUnitTests } from '@/services/testRunnerService';

import type { TestReport } from '@/types/testReport';

/** Where `src/test/logReporter.ts` writes the artifact, served from `public/`. */
const REPORT_URL = '/test-report.json';

function isTestReport(value: unknown): value is TestReport {
  if (typeof value !== 'object' || value === null) return false;
  const report = value as Partial<TestReport>;
  return typeof report.generatedAt === 'string' && Array.isArray(report.failures);
}

/**
 * Fetches the build-time artifact. A missing file is a normal state ("no run
 * yet"), not an error, so it resolves to `null` rather than throwing — that
 * keeps it out of the global query-error snackbar.
 */
async function fetchTestReport(signal: AbortSignal): Promise<TestReport | null> {
  const response = await fetch(REPORT_URL, { signal, cache: 'no-store' });
  if (!response.ok) return null;
  const parsed: unknown = await response.json();
  return isTestReport(parsed) ? parsed : null;
}

function FailureCard({ failure }: { failure: TestReport['failures'][number] }) {
  return (
    <Paper variant="outlined" sx={{ p: 2 }}>
      <Stack spacing={1}>
        <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap>
          <Chip size="small" color="error" label={failure.errorName} />
          <Typography variant="subtitle2" sx={{ fontFamily: 'monospace' }}>
            {failure.suite ? `${failure.suite} > ` : ''}
            {failure.name}
          </Typography>
          {failure.durationMs != null && (
            <Chip size="small" variant="outlined" label={`${String(failure.durationMs)}ms`} />
          )}
        </Stack>

        <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace' }}>
          {failure.file}
        </Typography>

        <Typography variant="body2">{failure.message}</Typography>

        {(failure.diff ?? failure.stack) && (
          <Box
            component="pre"
            sx={{
              m: 0,
              p: 1.5,
              fontSize: 12,
              lineHeight: 1.6,
              bgcolor: 'action.hover',
              borderRadius: 1,
              overflowX: 'auto',
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
            }}
          >
            {[failure.diff, failure.stack].filter(Boolean).join('\n\n')}
          </Box>
        )}
      </Stack>
    </Paper>
  );
}

/**
 * Unit-test failures from the last `pnpm test` run.
 *
 * Test results exist only at build time, so unlike the other two tabs this one
 * reads a file rather than the live log: `src/test/logReporter.ts` writes
 * `public/test-report.json` on every run, and this tab renders it.
 */
export function TestErrorsTab() {
  const queryClient = useQueryClient();
  const query = useQuery({
    queryKey: queryKeys.testReport,
    queryFn: ({ signal }) => fetchTestReport(signal),
    staleTime: 0,
    retry: false,
  });

  const run = useMutation({
    mutationFn: runUnitTests,
    // A failing suite is a successful run — the failures belong in the report,
    // so refetch either way. `invalidateQueries` re-reads the artifact Vitest
    // just rewrote, which is what updates the "run at" timestamp.
    onSettled: () => queryClient.invalidateQueries({ queryKey: queryKeys.testReport }),
    meta: { silenceGlobalError: true },
  });

  const report = query.data ?? null;
  const running = run.isPending;
  // Running the suite spawns a process on the dev host; that is maintenance,
  // not reading.
  const canRun = usePermission('diagnostics:manage');

  return (
    <Stack spacing={2}>
      <Typography variant="body2" color="text.secondary">
        Failures from the most recent run, read from <code>public/test-report.json</code>. The
        artifact is written by the reporter registered in <code>vite.config.ts</code>, so it
        refreshes whenever the suite runs — from the button here, from <code>pnpm test</code>, or in
        CI. Running from here needs the dev server, so the button is absent from production builds.
      </Typography>

      <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap>
        {report && (
          <>
            <Chip
              color={report.status === 'passed' ? 'success' : 'error'}
              label={report.status === 'passed' ? 'passing' : 'failing'}
            />
            <Chip variant="outlined" label={`${String(report.totals.passed)} passed`} />
            <Chip
              variant="outlined"
              color="error"
              label={`${String(report.totals.failed)} failed`}
            />
            <Chip variant="outlined" label={`${String(report.totals.skipped)} skipped`} />
            <Chip variant="outlined" label={`${String(report.totals.files)} files`} />
            <Chip variant="outlined" label={`${String(Math.round(report.durationMs))}ms`} />
            <Typography variant="caption" color="text.secondary">
              run {new Date(report.generatedAt).toLocaleString()}
            </Typography>
          </>
        )}
        <Box sx={{ flexGrow: 1 }} />
        <Button startIcon={<RefreshIcon />} onClick={() => void query.refetch()} disabled={running}>
          Refresh
        </Button>
        {canRunTests() && canRun && (
          <Button
            variant="contained"
            startIcon={running ? <CircularProgress size={16} color="inherit" /> : <PlayArrowIcon />}
            onClick={() => {
              run.mutate();
            }}
            disabled={running}
          >
            {running ? 'Running…' : 'Run unit tests'}
          </Button>
        )}
      </Stack>

      {running && (
        <Alert severity="info" variant="outlined" icon={<CircularProgress size={16} />}>
          Running the full suite. The report and its timestamp update when it finishes.
        </Alert>
      )}

      {run.isError && (
        <Alert severity="error" variant="outlined">
          <AlertTitle>Could not start the test run</AlertTitle>
          {run.error.message}
        </Alert>
      )}

      {/* The endpoint reports its own failure to start separately from a suite
          that simply failed — the latter is a normal outcome with a report. */}
      {run.data?.error !== undefined && (
        <Alert severity="error" variant="outlined">
          <AlertTitle>The test runner could not start</AlertTitle>
          {run.data.error}
        </Alert>
      )}

      {run.data && run.data.error === undefined && (
        <Alert severity={run.data.exitCode === 0 ? 'success' : 'warning'} variant="outlined">
          Run finished in {(run.data.durationMs / 1000).toFixed(1)}s with exit code{' '}
          {String(run.data.exitCode)}.
        </Alert>
      )}

      {query.isLoading && <Typography color="text.secondary">Loading report…</Typography>}

      {!query.isLoading && report === null && (
        <Alert severity="info" variant="outlined">
          <AlertTitle>No test report yet</AlertTitle>
          Run <code>pnpm test</code> to generate <code>public/test-report.json</code>, then press
          Refresh. In CI, publish the same file with the build so this tab reflects the pipeline.
        </Alert>
      )}

      {report?.unhandledErrors.map((message, index) => (
        <Alert key={index} severity="error" variant="outlined">
          <AlertTitle>Unhandled error outside a test</AlertTitle>
          {message}
        </Alert>
      ))}

      {report && report.failures.length === 0 && report.unhandledErrors.length === 0 && (
        <Alert severity="success" variant="outlined">
          All {report.totals.tests} tests passed in the last run.
        </Alert>
      )}

      {report?.failures.map((failure, index) => (
        <FailureCard key={`${failure.file}-${failure.name}-${String(index)}`} failure={failure} />
      ))}
    </Stack>
  );
}

// libraries/react-components/frontend/angular/src/app/features/admin/error-log/test-errors-tab.ts
import { httpResource } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

import { AuthStore } from '../../../core/auth/auth-store';
import { IS_DEV } from '../../../core/config/app-config';
import { SnackbarService } from '../../../shared/snackbar/snackbar.service';

import type { TestReport } from '../../../core/errors/test-report.types';

/**
 * Served by the dev-only runner sidecar, which reads
 * `.test-output/test-report.json`. Not a static asset: writing into `public/`
 * made the dev server reload the page mid-run.
 */
const REPORT_URL = '/test-report.json';

/** The dev-only endpoint; see `tools/test-runner-server.mjs`. */
const RUN_ENDPOINT = '/__run-unit-tests';

interface RunTestsResponse {
  ok: boolean;
  exitCode: number;
  durationMs: number;
  message?: string;
}

function isTestReport(value: unknown): value is TestReport {
  if (typeof value !== 'object' || value === null) return false;
  const report = value as Partial<TestReport>;
  return typeof report.generatedAt === 'string' && Array.isArray(report.failures);
}

/**
 * Unit test results.
 *
 * Tests run in Node, so the browser cannot observe them directly. The Vitest
 * reporter writes `.test-output/test-report.json` on every run and this tab reads it
 * — the artifact is the entire hand-off, and its type is the contract between
 * the two.
 *
 * A missing file is a normal state ("no run recorded"), not an error — which
 * is why a failed fetch renders the same guidance as a malformed report rather
 * than an alarming error panel.
 */
@Component({
  selector: 'app-test-errors-tab',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatButtonModule, MatIconModule, MatProgressSpinnerModule],
  template: `
    <div class="tests">
      <div class="tests__header">
        <p class="tests__lede">
          Written by the Vitest reporter on every run. Failures show the suite, file, message and
          diff — the same detail the terminal prints, without needing the terminal.
        </p>
        <div class="tests__actions">
          <button mat-stroked-button type="button" (click)="report.reload()">
            <mat-icon>refresh</mat-icon>
            Refresh
          </button>
          @if (canRun()) {
            <button mat-flat-button type="button" [disabled]="running()" (click)="runTests()">
              @if (running()) {
                <mat-spinner diameter="16" />
              } @else {
                <mat-icon>play_arrow</mat-icon>
              }
              {{ running() ? 'Running…' : 'Run unit tests' }}
            </button>
          }
        </div>
      </div>

      @if (runError()) {
        <p class="tests__error" role="alert">{{ runError() }}</p>
      }

      @if (report.isLoading()) {
        <p class="tests__muted">Loading the last report…</p>
      } @else if (validReport(); as result) {
        <div class="tests__summary" [class.tests__summary--failed]="result.status === 'failed'">
          <span class="tests__badge">{{ result.status }}</span>
          <span>{{ result.totals.passed }} passed</span>
          <span>{{ result.totals.failed }} failed</span>
          <span>{{ result.totals.skipped }} skipped</span>
          <span>{{ result.totals.files }} files</span>
          <span class="tests__when">
            {{ result.durationMs }}ms · {{ formatTime(result.generatedAt) }}
          </span>
        </div>

        @for (failure of result.failures; track failure.file + failure.name) {
          <article class="tests__failure">
            <header class="tests__failure-head">
              <span class="tests__badge tests__badge--error">{{ failure.errorName }}</span>
              <span class="tests__name">
                {{ failure.suite ? failure.suite + ' > ' : '' }}{{ failure.name }}
              </span>
              @if (failure.durationMs !== null) {
                <span class="tests__badge">{{ failure.durationMs }}ms</span>
              }
            </header>
            <p class="tests__file">{{ failure.file }}</p>
            <p class="tests__message">{{ failure.message }}</p>
            @if (failure.diff || failure.stack) {
              <pre class="tests__pre">{{ detailOf(failure) }}</pre>
            }
          </article>
        } @empty {
          <p class="tests__muted">
            No failures in the last run. Every one of the {{ result.totals.tests }} tests passed.
          </p>
        }

        @for (unhandled of result.unhandledErrors; track unhandled) {
          <pre class="tests__pre tests__pre--error">{{ unhandled }}</pre>
        }
      } @else {
        <p class="tests__muted">
          No test report available. Run <code>pnpm test</code> to produce one. The report is
          served by the dev runner, so this tab is populated under <code>pnpm dev</code> — under
          plain <code>pnpm start</code> there is nothing serving it.
        </p>
      }
    </div>
  `,
  styles: `
    :host { display: block; }
    .tests { display: flex; flex-direction: column; gap: 12px; }
    .tests__header {
      display: flex;
      flex-wrap: wrap;
      align-items: flex-start;
      justify-content: space-between;
      gap: 12px;
    }
    .tests__lede {
      margin: 0;
      max-width: 70ch;
      color: var(--mat-sys-on-surface-variant);
      font: var(--mat-sys-body-medium);
    }
    .tests__actions { display: flex; gap: 8px; }
    .tests__summary {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 12px;
      padding: 12px 16px;
      border-radius: 12px;
      background: var(--mat-sys-secondary-container);
      color: var(--mat-sys-on-secondary-container);
      font: var(--mat-sys-body-medium);
    }
    .tests__summary--failed {
      background: var(--mat-sys-error-container);
      color: var(--mat-sys-on-error-container);
    }
    .tests__when { margin-left: auto; opacity: 0.85; }
    .tests__badge {
      padding: 1px 10px;
      border-radius: 999px;
      background: var(--mat-sys-surface-container-highest);
      color: var(--mat-sys-on-surface-variant);
      font: var(--mat-sys-label-small);
      text-transform: uppercase;
    }
    .tests__badge--error {
      background: var(--mat-sys-error);
      color: var(--mat-sys-on-error);
    }
    .tests__failure {
      padding: 16px;
      border: 1px solid var(--mat-sys-outline-variant);
      border-radius: 12px;
      background: var(--mat-sys-surface-container-low);
    }
    .tests__failure-head {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 8px;
    }
    .tests__name {
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
      font-weight: 600;
    }
    .tests__file, .tests__message { margin: 8px 0 0; }
    .tests__file {
      color: var(--mat-sys-on-surface-variant);
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
      font-size: 0.8rem;
    }
    .tests__pre {
      margin: 12px 0 0;
      padding: 12px;
      border-radius: 8px;
      background: var(--mat-sys-surface-container-highest);
      font-size: 0.78rem;
      line-height: 1.6;
      /* Stack traces are wide; scroll them here, never the page. */
      overflow-x: auto;
      white-space: pre-wrap;
      overflow-wrap: anywhere;
    }
    .tests__pre--error { color: var(--mat-sys-error); }
    .tests__muted { margin: 0; color: var(--mat-sys-on-surface-variant); }
    .tests__error { margin: 0; color: var(--mat-sys-error); }
  `,
})
export class TestErrorsTab {
  private readonly auth = inject(AuthStore);
  private readonly snackbar = inject(SnackbarService);

  protected readonly running = signal(false);
  protected readonly runError = signal<string | null>(null);

  // `cache: no-store` matters: the point of Refresh is to see a *newer* file.
  protected readonly report = httpResource(() => ({
    url: REPORT_URL,
    headers: { 'Cache-Control': 'no-cache' },
  }));

  protected readonly validReport = computed<TestReport | null>(() => {
    const value = this.report.value();
    return isTestReport(value) ? value : null;
  });

  /**
   * Running the suite is a build action, not a read, so it needs the manage
   * capability — and the endpoint only exists under the dev server.
   */
  protected readonly canRun = computed(() => IS_DEV && this.auth.has('diagnostics:manage'));

  protected formatTime(iso: string): string {
    return new Date(iso).toLocaleString();
  }

  protected detailOf(failure: TestReport['failures'][number]): string {
    return [failure.diff, failure.stack].filter(Boolean).join('\n\n');
  }

  protected async runTests(): Promise<void> {
    this.running.set(true);
    this.runError.set(null);
    try {
      const response = await fetch(RUN_ENDPOINT, { method: 'POST' });
      if (!response.ok) {
        throw new Error(
          `The runner endpoint returned ${String(response.status)}. It exists only under \`pnpm start\`.`,
        );
      }
      const result = (await response.json()) as RunTestsResponse;
      // The suite has rewritten the artifact by now, so re-read it.
      this.report.reload();
      if (result.ok) {
        this.snackbar.success(`Tests passed in ${String(Math.round(result.durationMs / 1000))}s`);
      } else {
        this.snackbar.error(result.message ?? 'Tests failed — see the failures below.');
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.runError.set(message);
      this.snackbar.error(message);
    } finally {
      this.running.set(false);
    }
  }
}
