// libraries/react-components/frontend/angular/src/app/shared/grid/editing/dropdown-cell-editor.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { InlineEditBase } from './inline-edit-base';
import { InlineEditorShell } from './inline-editor-shell';

import type { EditorType } from './editing.types';

/**
 * In-cell dropdown, from `editorOptions` or a shared list resolved via
 * `optionsKey`. A native `<select>` rather than `mat-select`: the Material
 * version renders an overlay panel, which fights AG Grid's in-cell editor and
 * its focus handling for no gain at this size.
 */
@Component({
  selector: 'app-dropdown-cell-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [InlineEditorShell],
  template: `
    <app-inline-editor-shell
      [error]="errorText()"
      [saving]="saving()"
      [canApply]="canApply()"
      (apply)="apply()"
      (cancelled)="cancel()"
    >
      <select
        #field
        class="cell-select"
        [value]="draft()"
        [attr.aria-label]="params.column.getColDef().headerName ?? 'Value'"
        (change)="updateDraft($any($event.target).value)"
        (keydown)="onKeydown($event)"
      >
        @for (option of params.options ?? []; track option.value) {
          <option [value]="option.value">{{ option.label }}</option>
        }
      </select>
    </app-inline-editor-shell>
  `,
  styles: `
    .cell-select {
      width: 100%;
      border: 0;
      background: transparent;
      color: inherit;
      font: inherit;
      font-size: 0.875rem;
      outline: none;
    }
  `,
})
export class DropdownCellEditor<TData> extends InlineEditBase<TData, string> {
  protected readonly editorType: EditorType = 'dropdown';
}

// libraries/react-components/frontend/react/src/components/grid/editing/DropdownCellEditor.tsx
import MenuItem from '@mui/material/MenuItem';
import Select from '@mui/material/Select';
import { memo } from 'react';

import { useAutoFocus } from '@/hooks/useAutoFocus';

import { InlineEditorShell } from './InlineEditorShell';
import { useInlineEdit, type InlineEditorProps } from './useInlineEdit';

/**
 * In-cell dropdown editor. Options come from the column config
 * (`editorOptions`) or a shared list (`optionsKey` + grid `optionsMap`) —
 * never hardcoded here. The menu itself portals above the grid, but the
 * control renders inside the cell.
 */
export const DropdownCellEditor = memo(function DropdownCellEditor<TData>(
  props: InlineEditorProps<TData, string>,
) {
  const edit = useInlineEdit({ props, editorType: 'dropdown' });
  // MUI hands `inputRef` an imperative handle whose focus() targets the
  // display node, not the hidden form input.
  const focusRef = useAutoFocus<{ focus: () => void }>();
  const options = props.options ?? [];
  const label = props.column.getColDef().headerName;

  return (
    <InlineEditorShell
      error={edit.saveError ?? edit.validationError}
      saving={edit.saving}
      canApply={edit.canApply}
      onApply={edit.apply}
      onCancel={edit.cancel}
    >
      <Select
        inputRef={focusRef}
        fullWidth
        variant="standard"
        error={edit.validationError !== null}
        inputProps={{ 'aria-label': label }}
        value={edit.draft}
        onChange={(event) => edit.updateDraft(event.target.value)}
        sx={{ fontSize: '0.875rem' }}
      >
        {options.map((option) => (
          <MenuItem key={option.value} value={String(option.value)}>
            {option.label}
          </MenuItem>
        ))}
      </Select>
    </InlineEditorShell>
  );
});
