// libraries/archive/react-components/frontend/angular/src/app/features/auth/forbidden-page.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { ActivatedRoute, RouterLink } from '@angular/router';

import { AuthStore } from '../../core/auth/auth-store';
import { logWarning } from '../../core/errors/error-logger';

/**
 * Shown when an authenticated user reaches a route their role does not permit.
 *
 * Distinct from a 404 on purpose: "this exists but is not yours" is different
 * information from "this does not exist", and conflating them makes a
 * permissions problem look like a broken link.
 */
@Component({
  selector: 'app-forbidden-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MatButtonModule, MatIconModule, RouterLink],
  template: `
    <div class="forbidden">
      <mat-icon class="forbidden__icon" aria-hidden="true">lock_person</mat-icon>
      <h1>Not permitted</h1>
      <p>Your account does not have access to {{ from() ?? 'that page' }}.</p>
      <p class="forbidden__detail">
        Signed in as <strong>{{ auth.displayName() ?? 'unknown' }}</strong> with the
        <strong>{{ auth.role() ?? 'unknown' }}</strong> role. Ask an administrator if you need
        wider access.
      </p>
      <a matButton="filled" routerLink="/admin/dashboard">
        <mat-icon>home</mat-icon>
        Back to dashboard
      </a>
    </div>
  `,
  styles: `
    .forbidden {
      display: flex; flex-direction: column; align-items: center; gap: 12px;
      padding: 64px 16px; text-align: center;
    }
    .forbidden__icon { font-size: 56px; width: 56px; height: 56px; color: var(--mat-sys-tertiary); }
    .forbidden__detail { color: var(--mat-sys-on-surface-variant); font: var(--mat-sys-body-medium); }
  `,
})
export class ForbiddenPage {
  protected readonly auth = inject(AuthStore);
  private readonly route = inject(ActivatedRoute);

  /**
   * Read from the snapshot: the guard navigates here with `from` set once, and
   * the parameter cannot change while this page is displayed.
   */
  protected readonly from = signal(this.route.snapshot.queryParamMap.get('from'));

  constructor() {
    // A denial is worth recording: a legitimate user hitting this repeatedly
    // usually means their role is wrong, not that they are probing.
    const attempted = this.from();
    logWarning({
      channel: 'app',
      fileName: 'forbidden-page.ts',
      error: 'ACCESS_DENIED',
      errorDescription: `Role "${this.auth.role() ?? 'none'}" was denied ${attempted ?? 'a protected route'}.`,
      context: { kind: 'authorization', attempted, role: this.auth.role() },
    });
  }
}

// libraries/archive/react-components/frontend/react/src/features/auth/ForbiddenPage.tsx
import HomeIcon from '@mui/icons-material/Home';
import LockPersonIcon from '@mui/icons-material/LockPerson';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import { useEffect } from 'react';
import { Link as RouterLink, useLocation } from 'react-router-dom';

import { useAuth } from '@/store/authContext';
import { logWarning } from '@/utils/errorLogger';

/**
 * Shown when an authenticated user reaches a route their role does not permit.
 *
 * Distinct from the 404 view on purpose: "this exists but is not yours" is
 * different information from "this does not exist", and conflating them makes
 * a permissions problem look like a broken link.
 */
export function ForbiddenPage() {
  const { user } = useAuth();
  const location = useLocation();
  const from = (location.state as { from?: string } | null)?.from ?? null;

  // A denial is worth recording: a legitimate user hitting this repeatedly
  // usually means their role is wrong, not that they are probing.
  useEffect(() => {
    logWarning({
      channel: 'app',
      fileName: 'ForbiddenPage.tsx',
      error: 'ACCESS_DENIED',
      errorDescription: `Role "${user?.role ?? 'none'}" was denied ${from ?? 'a protected route'}.`,
      context: { kind: 'authorization', attempted: from, role: user?.role ?? null },
    });
  }, [from, user?.role]);

  return (
    <Box display="flex" justifyContent="center" alignItems="center" minHeight="60vh" px={2}>
      <Stack spacing={2} alignItems="center" textAlign="center" sx={{ maxWidth: 560 }}>
        <LockPersonIcon color="warning" sx={{ fontSize: 56 }} aria-hidden="true" />
        <Typography variant="h4">Not permitted</Typography>
        <Typography color="text.secondary">
          {from
            ? `Your account does not have access to ${from}.`
            : 'Your account does not have access to that page.'}
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Signed in as <strong>{user?.displayName ?? 'unknown'}</strong> with the{' '}
          <strong>{user?.role ?? 'unknown'}</strong> role. Ask an administrator if you need wider
          access.
        </Typography>
        <Button
          component={RouterLink}
          to="/admin/dashboard"
          variant="contained"
          startIcon={<HomeIcon />}
        >
          Back to dashboard
        </Button>
      </Stack>
    </Box>
  );
}
