// libraries/react-components/frontend/angular/src/app/features/auth/reset-password-page.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';

import { AuthService } from '../../core/auth/auth.service';
import { SnackbarService } from '../../shared/snackbar/snackbar.service';
import { getUserMessage, normalizeError } from '../../core/errors/normalize-error';

/**
 * A length floor and nothing else, matching the API.
 *
 * Composition rules ("one uppercase, one symbol") mostly produce `Password1!`
 * and measurably weaken real-world choices. NIST SP 800-63B recommends exactly
 * this: require length, drop the character classes.
 */
const MIN_LENGTH = 12;

@Component({
  selector: 'app-reset-password-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    RouterLink,
  ],
  template: `
    <div class="reset">
      <mat-card appearance="outlined" class="reset__card">
        <mat-card-header><mat-card-title>Choose a new password</mat-card-title></mat-card-header>
        <mat-card-content>
          @if (!token) {
            <!-- Say so here rather than letting the user type a password that
                 cannot be submitted. -->
            <p class="reset__error" role="alert">
              This reset link is missing its token. Request a new one.
            </p>
            <a routerLink="/forgot-password" class="reset__link">Request a new link</a>
          } @else {
            <p class="reset__lede">
              At least {{ minLength }} characters. A memorable phrase beats a short, complicated
              one.
            </p>

            <form [formGroup]="form" (ngSubmit)="submit()" novalidate>
              <mat-form-field appearance="outline" class="reset__field">
                <mat-label>New password</mat-label>
                <input
                  matInput
                  type="password"
                  formControlName="password"
                  autocomplete="new-password"
                />
                @if (form.controls.password.touched && form.controls.password.invalid) {
                  <mat-error>At least {{ minLength }} characters</mat-error>
                }
              </mat-form-field>

              <mat-form-field appearance="outline" class="reset__field">
                <mat-label>Confirm new password</mat-label>
                <input
                  matInput
                  type="password"
                  formControlName="confirm"
                  autocomplete="new-password"
                />
              </mat-form-field>

              @if (error()) {
                <p class="reset__error" role="alert">{{ error() }}</p>
              }

              <button matButton="filled" type="submit" [disabled]="busy()">
                @if (busy()) {
                  <mat-spinner diameter="16" />
                }
                {{ busy() ? 'Updating…' : 'Set new password' }}
              </button>

              <p class="reset__note">Setting a new password signs you out everywhere else.</p>
            </form>
          }
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: `
    .reset { display: flex; justify-content: center; padding: 48px 16px; }
    .reset__card { width: 400px; }
    .reset__field { width: 100%; }
    .reset__lede, .reset__note {
      color: var(--mat-sys-on-surface-variant);
      font: var(--mat-sys-body-small);
    }
    .reset__lede { margin: 0 0 16px; }
    .reset__note { margin: 12px 0 0; }
    .reset__error { color: var(--mat-sys-error); font: var(--mat-sys-body-small); margin: 0 0 12px; }
    .reset__link { color: var(--mat-sys-primary); }
  `,
})
export class ResetPasswordPage {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private readonly snackbar = inject(SnackbarService);
  private readonly fb = inject(FormBuilder);

  protected readonly minLength = MIN_LENGTH;
  protected readonly token = this.route.snapshot.queryParamMap.get('token') ?? '';
  protected readonly busy = signal(false);
  protected readonly error = signal<string | null>(null);

  protected readonly form = this.fb.nonNullable.group({
    password: ['', [Validators.required, Validators.minLength(MIN_LENGTH)]],
    confirm: [''],
  });

  protected async submit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    const { password, confirm } = this.form.getRawValue();
    if (password !== confirm) {
      this.error.set('The two passwords do not match.');
      return;
    }

    this.busy.set(true);
    this.error.set(null);
    try {
      const message = await this.auth.resetPassword(this.token, password);
      this.snackbar.success(message);
      await this.router.navigateByUrl('/login', { replaceUrl: true });
    } catch (caught) {
      const normalized = normalizeError(caught);
      this.error.set(normalized.message || getUserMessage(normalized));
    } finally {
      this.busy.set(false);
    }
  }
}

// libraries/archive/react-components/frontend/react/src/features/auth/ResetPasswordPage.tsx
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Link from '@mui/material/Link';
import Paper from '@mui/material/Paper';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';
import { useForm } from '@tanstack/react-form';
import { useState, type ChangeEvent, type FormEvent } from 'react';
import { Link as RouterLink, useNavigate, useSearchParams } from 'react-router-dom';
import { z } from 'zod';

import { fieldErrorText } from '@/components/forms/formHelpers';
import { snackbar } from '@/components/snackbar/snackbarBus';
import { resetPassword } from '@/services/authService';
import { getUserMessage, normalizeError } from '@/utils/errors';

/**
 * A length floor and nothing else, matching the API.
 *
 * Composition rules ("one uppercase, one symbol") mostly produce `Password1!`
 * and measurably weaken real-world choices. NIST SP 800-63B recommends exactly
 * this: require length, drop the character classes.
 */
const MIN_LENGTH = 12;
const passwordSchema = z.string().min(MIN_LENGTH, `At least ${String(MIN_LENGTH)} characters`);

export function ResetPasswordPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const token = searchParams.get('token') ?? '';
  const [submitError, setSubmitError] = useState<string | null>(null);

  const form = useForm({
    defaultValues: { password: '', confirm: '' },
    onSubmit: async ({ value }) => {
      setSubmitError(null);
      if (value.password !== value.confirm) {
        setSubmitError('The two passwords do not match.');
        return;
      }
      try {
        const message = await resetPassword(token, value.password);
        snackbar.success(message);
        void navigate('/login', { replace: true });
      } catch (error) {
        setSubmitError(getUserMessage(normalizeError(error)));
      }
    },
  });

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    event.stopPropagation();
    void form.handleSubmit();
  };

  // A missing token means the link was mistyped or truncated. Say so here
  // rather than letting the user type a password that cannot be submitted.
  if (!token) {
    return (
      <Box display="flex" justifyContent="center" mt={6}>
        <Paper sx={{ p: 4, width: 400 }}>
          <Alert severity="error" sx={{ mb: 2 }}>
            This reset link is missing its token. Request a new one.
          </Alert>
          <Link component={RouterLink} to="/forgot-password" variant="body2">
            Request a new link
          </Link>
        </Paper>
      </Box>
    );
  }

  return (
    <Box display="flex" justifyContent="center" mt={6}>
      <Paper sx={{ p: 4, width: 400 }}>
        <Typography variant="h5" gutterBottom>
          Choose a new password
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          At least {MIN_LENGTH} characters. A memorable phrase beats a short, complicated one.
        </Typography>

        <form onSubmit={handleSubmit} noValidate>
          <Stack spacing={2}>
            <form.Field name="password" validators={{ onBlur: passwordSchema }}>
              {(field) => (
                <TextField
                  label="New password"
                  type="password"
                  autoComplete="new-password"
                  // A sign-in page exists to be typed into, so focusing its
                  // first field is the documented exception to this rule rather
                  // than a violation of it.
                  // eslint-disable-next-line jsx-a11y/no-autofocus
                  autoFocus
                  fullWidth
                  value={field.state.value}
                  onChange={(event: ChangeEvent<HTMLInputElement>) =>
                    field.handleChange(event.target.value)
                  }
                  onBlur={field.handleBlur}
                  error={field.state.meta.isTouched && field.state.meta.errors.length > 0}
                  helperText={
                    field.state.meta.isTouched ? fieldErrorText(field.state.meta.errors) : ' '
                  }
                />
              )}
            </form.Field>

            <form.Field name="confirm">
              {(field) => (
                <TextField
                  label="Confirm new password"
                  type="password"
                  autoComplete="new-password"
                  fullWidth
                  value={field.state.value}
                  onChange={(event: ChangeEvent<HTMLInputElement>) =>
                    field.handleChange(event.target.value)
                  }
                  onBlur={field.handleBlur}
                  helperText=" "
                />
              )}
            </form.Field>

            {submitError !== null && <Alert severity="error">{submitError}</Alert>}

            <form.Subscribe selector={(state) => state.isSubmitting}>
              {(isSubmitting) => (
                <Button type="submit" variant="contained" disabled={isSubmitting} fullWidth>
                  {isSubmitting ? 'Updating…' : 'Set new password'}
                </Button>
              )}
            </form.Subscribe>

            <Typography variant="caption" color="text.secondary">
              Setting a new password signs you out everywhere else.
            </Typography>
          </Stack>
        </form>
      </Paper>
    </Box>
  );
}
