// libraries/archive/react-components/frontend/react/src/features/public/HomePage.tsx
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import PaletteIcon from '@mui/icons-material/Palette';
import RocketLaunchIcon from '@mui/icons-material/RocketLaunch';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import { useTheme, type Theme } from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import { useMemo, type ReactNode } from 'react';
import { Link as RouterLink } from 'react-router-dom';

import { glassAccents } from '@/components/glass/glassAccents';
import { GlassCard } from '@/components/glass/GlassCard';
import { ImageCarousel, type CarouselSlide } from '@/components/glass/ImageCarousel';
import { PageContainer } from '@/components/glass/PageContainer';
import { ScrollReveal } from '@/components/motion/ScrollReveal';
import { useAuth } from '@/store/authContext';

/* ------------------------- content (CodeGen port) ------------------------ */

const slides: CarouselSlide[] = [
  {
    image:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=80',
    title: 'Insightful Dashboards',
    caption: 'Real-time data, beautifully rendered.',
  },
  {
    image:
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&q=80',
    title: 'Built for Teams',
    caption: 'Collaborate with reusable, typed components.',
  },
  {
    image:
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1400&q=80',
    title: 'Polished by Design',
    caption: 'A consistent glassmorphism aesthetic throughout.',
  },
];

const featureCards = [
  {
    image:
      'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    title: 'Analytics',
    body: 'Track the metrics that matter with live charts and KPI cards.',
  },
  {
    image:
      'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=800&q=80',
    title: 'Collaboration',
    body: 'Shared workspaces with role-based, protected admin access.',
  },
  {
    image:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    title: 'Automation',
    body: 'Reliable data fetching with caching and graceful error states.',
  },
];

const kpis = [
  { label: 'Components', value: '40+', accent: glassAccents.violet },
  { label: 'Theme styles', value: '3', accent: glassAccents.pink },
  { label: 'Data grids', value: '5', accent: glassAccents.teal },
  { label: 'Charts', value: 'Live', accent: glassAccents.amber },
];

/* ------------------------------- chart ---------------------------------- */

/** Theme-aware Highcharts options: transparent background, palette colors. */
function buildActivityOptions(theme: Theme): Highcharts.Options {
  const { text, divider, primary, secondary } = theme.palette;
  const axis = {
    labels: { style: { color: text.secondary } },
    lineColor: divider,
    tickColor: divider,
    gridLineColor: divider,
  } satisfies Highcharts.XAxisOptions & Highcharts.YAxisOptions;

  return {
    chart: {
      type: 'areaspline',
      backgroundColor: 'transparent',
      height: 260,
      style: { fontFamily: theme.typography.fontFamily },
    },
    title: { text: undefined },
    xAxis: { ...axis, categories: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    yAxis: { ...axis, title: { text: undefined } },
    legend: {
      itemStyle: { color: text.secondary },
      itemHoverStyle: { color: text.primary },
    },
    tooltip: {
      backgroundColor: theme.palette.background.paper,
      borderColor: divider,
      style: { color: text.primary },
    },
    plotOptions: {
      areaspline: { marker: { enabled: false }, fillOpacity: 0.25 },
    },
    series: [
      {
        type: 'areaspline',
        name: 'Active users',
        color: primary.main,
        data: [32, 45, 41, 58, 63, 52, 71],
      },
      {
        type: 'areaspline',
        name: 'Sessions',
        color: secondary.main,
        data: [21, 30, 28, 39, 44, 38, 52],
      },
    ],
    credits: { enabled: false },
  };
}

/* --------------------------- highlight card ------------------------------ */

interface HighlightCardProps {
  icon: ReactNode;
  title: string;
  body: string;
  buttonLabel: string;
  to: string;
}

/** The hero-style CTA card (icon + title + body + action button). */
function HighlightCard({ icon, title, body, buttonLabel, to }: HighlightCardProps) {
  return (
    <GlassCard sx={{ maxWidth: 520, width: '100%' }}>
      <CardContent sx={{ p: 4 }}>
        <Stack spacing={2} alignItems="flex-start">
          {icon}
          <Typography variant="h5">{title}</Typography>
          <Typography color="text.secondary">{body}</Typography>
          <Button
            variant="contained"
            size="large"
            endIcon={<ArrowForwardIcon />}
            component={RouterLink}
            to={to}
          >
            {buttonLabel}
          </Button>
        </Stack>
      </CardContent>
    </GlassCard>
  );
}

/* -------------------------------- page ---------------------------------- */

/**
 * Public landing page, ported from the CodeGen project (carousel + feature
 * cards) and extended with themed KPI + chart glass cards. All surfaces
 * follow the active theme settings (plain / glass / 3D Gradient Glass).
 */
export function HomePage() {
  const theme = useTheme();
  const { isAuthenticated } = useAuth();
  const activityOptions = useMemo(() => buildActivityOptions(theme), [theme]);

  return (
    <PageContainer
      title="Welcome to Idol-Promo"
      subtitle="A fully featured dashboard with a polished, theme-aware aesthetic."
      action={
        <Button
          variant="contained"
          endIcon={<ArrowForwardIcon />}
          component={RouterLink}
          to={isAuthenticated ? '/admin/dashboard' : '/login'}
        >
          {isAuthenticated ? 'Go to Admin' : 'Sign in'}
        </Button>
      }
    >
      <ScrollReveal>
        <Box sx={{ mb: 5 }}>
          <ImageCarousel slides={slides} />
        </Box>
      </ScrollReveal>

      <ScrollReveal>
        <Typography variant="h5" sx={{ fontWeight: 600, mb: 2 }}>
          What you can build
        </Typography>
        <Grid container spacing={3} sx={{ mb: 5 }}>
          {featureCards.map((card) => (
            <Grid key={card.title} size={{ xs: 12, sm: 6, md: 4 }}>
              <GlassCard interactive sx={{ height: '100%' }}>
                <CardMedia component="img" height="180" image={card.image} alt={card.title} />
                <CardContent>
                  <Typography variant="h6" sx={{ fontWeight: 600 }}>
                    {card.title}
                  </Typography>
                  <Typography variant="body2" color="text.secondary">
                    {card.body}
                  </Typography>
                </CardContent>
              </GlassCard>
            </Grid>
          ))}
        </Grid>
      </ScrollReveal>

      {/* ── Alternating highlight rows: card ⇄ text ─────────────────────── */}
      <Grid container spacing={4} alignItems="center" sx={{ mb: 5 }}>
        {/* Row 1: card left, text right */}
        <Grid size={{ xs: 12, md: 6 }}>
          <ScrollReveal direction="left">
            <Box display="flex" justifyContent={{ xs: 'center', md: 'flex-start' }}>
              <HighlightCard
                icon={<RocketLaunchIcon color="primary" fontSize="large" />}
                title={isAuthenticated ? 'Welcome back!' : 'Get started — set up your project'}
                body={
                  isAuthenticated
                    ? 'Your project is set up. Jump straight into the admin area.'
                    : 'Sign in to configure your workspace and manage products, users, and settings.'
                }
                buttonLabel={isAuthenticated ? 'Go to Admin' : 'Set up your project'}
                to={isAuthenticated ? '/admin/dashboard' : '/login'}
              />
            </Box>
          </ScrollReveal>
        </Grid>
        <Grid size={{ xs: 12, md: 6 }}>
          <ScrollReveal direction="right" delay={0.15}>
            <Typography variant="h5" sx={{ fontWeight: 700 }} gutterBottom>
              A protected admin console, out of the box
            </Typography>
            <Typography color="text.secondary">
              Authentication, routing and error boundaries are already wired. Behind the login you
              get master-data management with editable AG Grid tables, quick-add forms with
              validation, and query-cached data fetching with optimistic or pessimistic saves —
              everything a back-office app needs from day one.
            </Typography>
          </ScrollReveal>
        </Grid>

        {/* Row 2: text left, card right (order swaps on md+) */}
        <Grid size={{ xs: 12, md: 6 }} order={{ xs: 2, md: 1 }}>
          <ScrollReveal direction="left" delay={0.15}>
            <Typography variant="h5" sx={{ fontWeight: 700 }} gutterBottom>
              Three theme styles, one design system
            </Typography>
            <Typography color="text.secondary">
              Switch between Plain, Gradient Glass and 3D Gradient Glass, pick your own primary and
              secondary colors, and every surface — cards, grids, dialogs, charts — follows
              instantly. Preferences persist across sessions, in light and dark mode.
            </Typography>
          </ScrollReveal>
        </Grid>
        <Grid size={{ xs: 12, md: 6 }} order={{ xs: 1, md: 2 }}>
          <ScrollReveal direction="right">
            <Box display="flex" justifyContent={{ xs: 'center', md: 'flex-end' }}>
              <HighlightCard
                icon={<PaletteIcon color="secondary" fontSize="large" />}
                title="Make it yours"
                body="Explore the theme system — styles, colors and modes — and see the whole app restyle in real time."
                buttonLabel="Learn more"
                to="/about"
              />
            </Box>
          </ScrollReveal>
        </Grid>
      </Grid>

      <ScrollReveal>
        <Typography variant="h5" sx={{ fontWeight: 600, mb: 2 }}>
          At a glance
        </Typography>
        <Grid container spacing={3}>
          {kpis.map((kpi) => (
            <Grid key={kpi.label} size={{ xs: 6, md: 3 }}>
              <GlassCard interactive accent={kpi.accent} sx={{ height: '100%' }}>
                <CardContent>
                  <Stack spacing={0.5}>
                    <Typography variant="h4" sx={{ fontWeight: 700 }}>
                      {kpi.value}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      {kpi.label}
                    </Typography>
                  </Stack>
                </CardContent>
              </GlassCard>
            </Grid>
          ))}

          <Grid size={{ xs: 12 }}>
            <GlassCard sx={{ p: { xs: 2, md: 3 } }}>
              <Typography variant="h6" sx={{ fontWeight: 600, mb: 1 }}>
                Weekly activity
              </Typography>
              <HighchartsReact highcharts={Highcharts} options={activityOptions} />
            </GlassCard>
          </Grid>
        </Grid>
      </ScrollReveal>
    </PageContainer>
  );
}

// libraries/archive/react-components/frontend/angular/src/app/features/public/home-page.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';

import { AuthStore } from '../../core/auth/auth-store';
import { AccentCard } from '../../shared/accent-card/accent-card';
import { GenericChart } from '../../shared/generic-chart/generic-chart';
import { PageContainer } from '../../shared/page-container/page-container';

import type { AccentName } from '../../shared/accent-card/accent-card';
import type { ChartSeries } from '../../shared/generic-chart/chart.types';

interface FeatureCard {
  readonly icon: string;
  readonly title: string;
  readonly body: string;
}

interface Kpi {
  readonly label: string;
  readonly value: string;
  readonly accent: AccentName;
}

const FEATURES: readonly FeatureCard[] = [
  {
    icon: 'insights',
    title: 'Analytics',
    body: 'Track the metrics that matter with live charts and KPI cards.',
  },
  {
    icon: 'groups',
    title: 'Collaboration',
    body: 'Shared workspaces with role-based, protected admin access.',
  },
  {
    icon: 'bolt',
    title: 'Automation',
    body: 'Reliable data fetching with caching and graceful error states.',
  },
];

const KPIS: readonly Kpi[] = [
  { label: 'Components', value: '40+', accent: 'violet' },
  { label: 'Signals only', value: '100%', accent: 'pink' },
  { label: 'Data grids', value: '5', accent: 'teal' },
  { label: 'Charts', value: 'Live', accent: 'amber' },
];

/** Weekly activity, matching the React landing page's demo series. */
const ACTIVITY: readonly ChartSeries[] = [
  {
    id: 'active-users',
    name: 'Active users',
    type: 'area',
    data: [32, 45, 41, 58, 63, 52, 71].map((y, index) => ({
      id: `au-${index}`,
      x: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][index],
      y,
    })),
  },
  {
    id: 'sessions',
    name: 'Sessions',
    type: 'area',
    data: [21, 30, 28, 39, 44, 38, 52].map((y, index) => ({
      id: `s-${index}`,
      x: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][index],
      y,
    })),
  },
];

/**
 * Public landing page.
 *
 * The React original leaned on `ScrollReveal` (framer-motion) and an image
 * carousel pulling from Unsplash. Both are dropped here: the animation library
 * has no place in a signals-only port, and the remote images made the page's
 * first paint depend on a third-party host.
 */
@Component({
  selector: 'app-home-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    AccentCard,
    GenericChart,
    MatButtonModule,
    MatCardModule,
    MatIconModule,
    PageContainer,
    RouterLink,
  ],
  template: `
    <app-page-container
      title="Welcome to Idol-Promo"
      subtitle="A fully featured dashboard, rebuilt on Angular Signals."
    >
      <a page-action mat-flat-button [routerLink]="ctaLink()">
        {{ ctaLabel() }}
        <mat-icon iconPositionEnd>arrow_forward</mat-icon>
      </a>

      <h2 class="home__section">What you can build</h2>
      <div class="home__grid home__grid--three">
        @for (feature of features; track feature.title) {
          <app-accent-card interactive>
            <mat-card-content class="home__feature">
              <mat-icon class="home__feature-icon" aria-hidden="true">{{ feature.icon }}</mat-icon>
              <h3>{{ feature.title }}</h3>
              <p>{{ feature.body }}</p>
            </mat-card-content>
          </app-accent-card>
        }
      </div>

      <div class="home__highlight">
        <app-accent-card accent="violet">
          <mat-card-content class="home__highlight-card">
            <mat-icon class="home__feature-icon" aria-hidden="true">rocket_launch</mat-icon>
            <h3>{{ highlightTitle() }}</h3>
            <p>{{ highlightBody() }}</p>
            <a mat-flat-button [routerLink]="ctaLink()">
              {{ ctaLabel() }}
              <mat-icon iconPositionEnd>arrow_forward</mat-icon>
            </a>
          </mat-card-content>
        </app-accent-card>
        <div>
          <h2 class="home__section">A protected admin console, out of the box</h2>
          <p class="home__prose">
            Authentication, routing and error handling are already wired. Behind the login you get
            master-data management with editable AG Grid tables, schema-driven forms with
            validation, and cached data fetching built on <code>httpResource</code> — everything a
            back-office app needs from day one.
          </p>
        </div>
      </div>

      <h2 class="home__section">At a glance</h2>
      <div class="home__grid home__grid--four">
        @for (kpi of kpis; track kpi.label) {
          <app-accent-card interactive [accent]="kpi.accent">
            <mat-card-content>
              <p class="home__kpi-value">{{ kpi.value }}</p>
              <p class="home__kpi-label">{{ kpi.label }}</p>
            </mat-card-content>
          </app-accent-card>
        }
      </div>

      <app-accent-card>
        <mat-card-content>
          <h3 class="home__chart-title">Weekly activity</h3>
          <app-generic-chart
            [series]="activity"
            [height]="260"
            [xAxis]="{ categories: days }"
            ariaLabel="Weekly activity: active users and sessions"
          />
        </mat-card-content>
      </app-accent-card>
    </app-page-container>
  `,
  styles: `
    .home__section {
      margin: 40px 0 16px;
      font: var(--mat-sys-headline-small);
      font-weight: 600;
    }
    .home__section:first-of-type { margin-top: 0; }
    .home__grid {
      display: grid;
      gap: 24px;
      margin-bottom: 8px;
    }
    .home__grid--three { grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); }
    .home__grid--four { grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }
    .home__feature, .home__highlight-card {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      gap: 8px;
    }
    .home__feature h3, .home__highlight-card h3 {
      margin: 0;
      font: var(--mat-sys-title-medium);
      font-weight: 700;
    }
    .home__feature p, .home__highlight-card p {
      margin: 0;
      color: var(--mat-sys-on-surface-variant);
    }
    .home__highlight-card a { margin-top: 8px; }
    .home__feature-icon {
      --mat-icon-color: var(--mat-sys-primary);
      width: 40px;
      height: 40px;
      font-size: 40px;
    }
    .home__highlight {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      align-items: center;
      gap: 32px;
      margin: 40px 0;
    }
    .home__prose {
      margin: 0;
      color: var(--mat-sys-on-surface-variant);
    }
    .home__kpi-value {
      margin: 0;
      font: var(--mat-sys-headline-medium);
      font-weight: 700;
    }
    .home__kpi-label {
      margin: 4px 0 0;
      color: var(--mat-sys-on-surface-variant);
    }
    .home__chart-title {
      margin: 0 0 8px;
      font: var(--mat-sys-title-medium);
      font-weight: 600;
    }
  `,
})
export class HomePage {
  private readonly auth = inject(AuthStore);

  protected readonly features = FEATURES;
  protected readonly kpis = KPIS;
  protected readonly activity = ACTIVITY;
  protected readonly days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  protected readonly ctaLink = computed(() =>
    this.auth.isAuthenticated() ? '/admin/dashboard' : '/login',
  );
  protected readonly ctaLabel = computed(() =>
    this.auth.isAuthenticated() ? 'Go to admin' : 'Sign in',
  );
  protected readonly highlightTitle = computed(() =>
    this.auth.isAuthenticated() ? 'Welcome back!' : 'Get started — set up your project',
  );
  protected readonly highlightBody = computed(() =>
    this.auth.isAuthenticated()
      ? 'Your project is set up. Jump straight into the admin area.'
      : 'Sign in to configure your workspace and manage products, users and settings.',
  );
}
