// libraries/archive/react-components/frontend/angular/src/app/features/admin/error-log/error-log-toolbar.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';

import { AuthStore } from '../../../core/auth/auth-store';
import { downloadLogs } from '../../../core/errors/error-logger';

import type { ChannelView } from './channel-view';
import type { ErrorLogLevel } from '../../../core/errors/error-log.types';

const LEVELS: (ErrorLogLevel | 'all')[] = ['all', 'error', 'warning', 'info', 'debug'];

/**
 * Counts, filters and export controls, shared by all three tabs — so a filter
 * or export format added here reaches every channel at once.
 *
 * Export writes what is currently *filtered*, not the whole log: the file
 * should match what the operator is looking at.
 */
@Component({
  selector: 'app-error-log-toolbar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    MatButtonModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatSelectModule,
    MatSlideToggleModule,
  ],
  template: `
    <div class="toolbar">
      <div class="toolbar__counts">
        @for (entry of countEntries(); track entry.level) {
          <span class="toolbar__chip" [class]="'toolbar__chip--' + entry.level">
            {{ entry.level }}: {{ entry.count }}
          </span>
        }
        <span class="toolbar__chip">showing {{ view().filtered().length }}</span>
      </div>

      <div class="toolbar__controls">
        <mat-form-field appearance="outline" subscriptSizing="dynamic" class="toolbar__search">
          <mat-label>Search</mat-label>
          <input
            matInput
            type="search"
            [value]="view().search()"
            (input)="view().search.set($any($event.target).value)"
            placeholder="Message, endpoint, file…"
          />
          <mat-icon matSuffix>search</mat-icon>
        </mat-form-field>

        <mat-form-field appearance="outline" subscriptSizing="dynamic" class="toolbar__level">
          <mat-label>Level</mat-label>
          <mat-select
            [value]="view().level()"
            (selectionChange)="view().level.set($any($event).value)"
          >
            @for (option of levels; track option) {
              <mat-option [value]="option">{{ option }}</mat-option>
            }
          </mat-select>
        </mat-form-field>

        <mat-slide-toggle
          [checked]="view().grouped()"
          (change)="view().grouped.set($any($event).checked)"
        >
          Group duplicates
        </mat-slide-toggle>

        <button mat-stroked-button type="button" (click)="view().refresh()">
          <mat-icon>refresh</mat-icon>
          Refresh
        </button>

        <button mat-stroked-button type="button" (click)="exportLogs('log')">
          <mat-icon>download</mat-icon>
          Export
        </button>

        <!--
          Clearing destroys evidence someone else may still need, so it is gated
          on its own capability rather than on being able to read the log.
        -->
        @if (canManage()) {
          <button
            mat-stroked-button
            type="button"
            [disabled]="view().entries().length === 0"
            (click)="view().clearChannel()"
          >
            <mat-icon>delete_sweep</mat-icon>
            Clear {{ channelLabel() }}
          </button>
        }
      </div>
    </div>
  `,
  styles: `
    :host { display: block; margin-bottom: 12px; }
    .toolbar { display: flex; flex-direction: column; gap: 12px; }
    .toolbar__counts, .toolbar__controls {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      gap: 8px;
    }
    .toolbar__controls { gap: 12px; }
    .toolbar__chip {
      padding: 2px 10px;
      border-radius: 999px;
      background: var(--mat-sys-surface-container-highest);
      color: var(--mat-sys-on-surface-variant);
      font: var(--mat-sys-label-small);
    }
    .toolbar__chip--error {
      background: var(--mat-sys-error-container);
      color: var(--mat-sys-on-error-container);
    }
    .toolbar__chip--warning {
      background: var(--mat-sys-tertiary-container);
      color: var(--mat-sys-on-tertiary-container);
    }
    .toolbar__search { min-width: 260px; }
    .toolbar__level { width: 140px; }
  `,
})
export class ErrorLogToolbar {
  private readonly auth = inject(AuthStore);

  readonly view = input.required<ChannelView>();
  readonly channelLabel = input('channel');

  protected readonly levels = LEVELS;

  protected readonly canManage = computed(() => this.auth.has('diagnostics:manage'));

  protected readonly countEntries = computed(() =>
    Object.entries(this.view().counts()).map(([level, count]) => ({ level, count })),
  );

  protected exportLogs(format: 'log' | 'json'): void {
    downloadLogs(format, this.view().filtered());
  }
}

// libraries/react-components/frontend/react/src/components/errors/ErrorLogToolbar.tsx
import DeleteSweepIcon from '@mui/icons-material/DeleteSweep';
import DownloadIcon from '@mui/icons-material/Download';
import RefreshIcon from '@mui/icons-material/Refresh';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import FormControl from '@mui/material/FormControl';
import FormControlLabel from '@mui/material/FormControlLabel';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import Select from '@mui/material/Select';
import Stack from '@mui/material/Stack';
import Switch from '@mui/material/Switch';
import TextField from '@mui/material/TextField';

import { usePermission } from '@/auth/usePermission';
import { downloadLogs } from '@/utils/errorLogger';

import type { ErrorLogEntry, ErrorLogLevel } from '@/types/errorLog';

interface ErrorLogToolbarProps {
  entries: readonly ErrorLogEntry[];
  filtered: readonly ErrorLogEntry[];
  counts: Record<string, number>;
  level: ErrorLogLevel | 'all';
  onLevelChange: (level: ErrorLogLevel | 'all') => void;
  search: string;
  onSearchChange: (search: string) => void;
  grouped: boolean;
  onGroupedChange: (grouped: boolean) => void;
  onRefresh: () => void;
  onClear: () => void;
  /** Names the channel in the clear button, e.g. "API". */
  channelLabel: string;
}

/**
 * Counts, filters and export controls. Shared by all three tabs so a behavior
 * added here (a new filter, a new export format) reaches every channel at once.
 *
 * Export writes whatever is currently filtered, not the whole log — the export
 * should match what the operator is looking at.
 */
export function ErrorLogToolbar({
  entries,
  filtered,
  counts,
  level,
  onLevelChange,
  search,
  onSearchChange,
  grouped,
  onGroupedChange,
  onRefresh,
  onClear,
  channelLabel,
}: ErrorLogToolbarProps) {
  // Clearing a channel destroys evidence other people may still need, so it is
  // a separate capability from being able to read the log.
  const canManage = usePermission('diagnostics:manage');

  return (
    <Stack direction="row" spacing={1} sx={{ mb: 2, flexWrap: 'wrap', gap: 1 }} alignItems="center">
      <Chip label={`total ${String(entries.length)}`} />
      <Chip color="error" variant="outlined" label={`error ${String(counts.error ?? 0)}`} />
      <Chip color="warning" variant="outlined" label={`warning ${String(counts.warning ?? 0)}`} />
      <Chip color="info" variant="outlined" label={`info ${String(counts.info ?? 0)}`} />

      <TextField
        size="small"
        label="Search"
        placeholder="message, file, endpoint"
        value={search}
        onChange={(event) => {
          onSearchChange(event.target.value);
        }}
        sx={{ minWidth: 220 }}
      />

      <FormControl size="small" sx={{ minWidth: 130 }}>
        <InputLabel id={`level-filter-${channelLabel}`}>Level</InputLabel>
        <Select
          labelId={`level-filter-${channelLabel}`}
          label="Level"
          value={level}
          onChange={(event) => {
            onLevelChange(event.target.value);
          }}
        >
          <MenuItem value="all">All</MenuItem>
          <MenuItem value="error">Error</MenuItem>
          <MenuItem value="warning">Warning</MenuItem>
          <MenuItem value="info">Info</MenuItem>
          <MenuItem value="debug">Debug</MenuItem>
        </Select>
      </FormControl>

      <FormControlLabel
        control={
          <Switch
            size="small"
            checked={grouped}
            onChange={(event) => {
              onGroupedChange(event.target.checked);
            }}
          />
        }
        label="Group"
      />

      <Box sx={{ flexGrow: 1 }} />

      <Button startIcon={<RefreshIcon />} onClick={onRefresh}>
        Refresh
      </Button>
      <Button
        startIcon={<DownloadIcon />}
        variant="outlined"
        onClick={() => {
          downloadLogs('log', filtered);
        }}
        disabled={filtered.length === 0}
      >
        .log
      </Button>
      <Button
        startIcon={<DownloadIcon />}
        variant="outlined"
        onClick={() => {
          downloadLogs('json', filtered);
        }}
        disabled={filtered.length === 0}
      >
        .json
      </Button>
      {canManage && (
        <Button
          startIcon={<DeleteSweepIcon />}
          color="error"
          variant="outlined"
          onClick={onClear}
          disabled={entries.length === 0}
        >
          Clear {channelLabel}
        </Button>
      )}
    </Stack>
  );
}
