// libraries/react-components/frontend/angular/src/app/features/auth/login-page.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';

import { AuthService } from '../../core/auth/auth.service';
import { IS_DEV } from '../../core/config/app-config';
import { SnackbarService } from '../../shared/snackbar/snackbar.service';
import { getUserMessage, normalizeError } from '../../core/errors/normalize-error';

const DEFAULT_DESTINATION = '/admin/dashboard';

@Component({
  selector: 'app-login-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReactiveFormsModule,
    MatCardModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    RouterLink,
  ],
  template: `
    <div class="login">
      <mat-card appearance="outlined" class="login__card">
        <mat-card-header><mat-card-title>Sign in</mat-card-title></mat-card-header>
        <mat-card-content>
          @if (isDev) {
            <p class="login__hint">
              Seeded accounts: <strong>admin&#64;idol-promo.test</strong> and
              <strong>user&#64;idol-promo.test</strong>, password <strong>Password123!</strong>
            </p>
          }

          <!-- novalidate: the messages come from the form, not the browser. -->
          <form [formGroup]="form" (ngSubmit)="submit()" novalidate>
            <mat-form-field appearance="outline" class="login__field">
              <mat-label>Email</mat-label>
              <!--
                "username" is the correct autocomplete token for the identifier
                field even when it holds an email — password managers key off it
                together with current-password below.
              -->
              <input
                matInput
                type="email"
                formControlName="email"
                autocomplete="username"
                required
              />
              @if (form.controls.email.touched && form.controls.email.invalid) {
                <mat-error>Enter a valid email address</mat-error>
              }
            </mat-form-field>

            <mat-form-field appearance="outline" class="login__field">
              <mat-label>Password</mat-label>
              <input
                matInput
                type="password"
                formControlName="password"
                autocomplete="current-password"
                required
              />
              @if (form.controls.password.touched && form.controls.password.invalid) {
                <mat-error>Password is required</mat-error>
              }
            </mat-form-field>

            <div class="login__row">
              <mat-checkbox formControlName="rememberMe">Remember me</mat-checkbox>
              <a routerLink="/forgot-password" class="login__link">Forgot password?</a>
            </div>

            @if (error()) {
              <p class="login__error" role="alert">{{ error() }}</p>
            }

            <button matButton="filled" type="submit" [disabled]="busy()">
              @if (busy()) {
                <mat-spinner diameter="16" />
              }
              {{ busy() ? 'Signing in…' : 'Sign in' }}
            </button>

            <p class="login__note">
              “Remember me” keeps you signed in for 30 days. Leave it off and the session ends when
              the browser closes.
            </p>
          </form>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: `
    .login { display: flex; justify-content: center; padding: 48px 16px; }
    .login__card { width: 400px; }
    .login__field { width: 100%; }
    .login__row {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 12px;
    }
    .login__link { color: var(--mat-sys-primary); font: var(--mat-sys-body-small); }
    .login__hint {
      background: var(--mat-sys-secondary-container);
      color: var(--mat-sys-on-secondary-container);
      padding: 10px 12px;
      border-radius: 8px;
      font: var(--mat-sys-body-small);
      margin: 0 0 16px;
    }
    .login__error {
      color: var(--mat-sys-error);
      font: var(--mat-sys-body-small);
      margin: 0 0 12px;
    }
    .login__note {
      margin: 12px 0 0;
      color: var(--mat-sys-on-surface-variant);
      font: var(--mat-sys-body-small);
    }
  `,
})
export class LoginPage {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private readonly snackbar = inject(SnackbarService);
  private readonly fb = inject(FormBuilder);

  protected readonly isDev = IS_DEV;
  protected readonly busy = signal(false);
  protected readonly error = signal<string | null>(null);

  protected readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', Validators.required],
    rememberMe: [false],
  });

  protected async submit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.busy.set(true);
    this.error.set(null);
    try {
      await this.auth.login(this.form.getRawValue());
      this.snackbar.success('Welcome back!');
      const returnTo = this.route.snapshot.queryParamMap.get('returnTo') ?? DEFAULT_DESTINATION;
      await this.router.navigateByUrl(returnTo, { replaceUrl: true });
    } catch (caught) {
      // The API's own message is the useful one here ("Email or password is
      // incorrect", "Too many failed attempts"). `getUserMessage` maps every
      // 401 to a generic "please sign in", which is right for an expired
      // session and useless on the form you are already signing in with.
      const normalized = normalizeError(caught);
      this.error.set(normalized.message || getUserMessage(normalized));
    } finally {
      this.busy.set(false);
    }
  }
}

// libraries/react-components/frontend/react/src/features/auth/LoginPage.tsx
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Checkbox from '@mui/material/Checkbox';
import FormControlLabel from '@mui/material/FormControlLabel';
import Link from '@mui/material/Link';
import Paper from '@mui/material/Paper';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';
import { useForm } from '@tanstack/react-form';
import { useState, type ChangeEvent, type FormEvent } from 'react';
import { Link as RouterLink, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { z } from 'zod';

import { fieldErrorText } from '@/components/forms/formHelpers';
import { snackbar } from '@/components/snackbar/snackbarBus';
import { useAuth } from '@/store/authContext';
import { normalizeError, getUserMessage } from '@/utils/errors';

const emailSchema = z.string().email('Enter a valid email address');
const passwordSchema = z.string().min(1, 'Password is required');

const DEFAULT_DESTINATION = '/admin/dashboard';

interface LocationState {
  returnTo?: string;
}

export function LoginPage() {
  const { login, isAuthenticated } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [submitError, setSubmitError] = useState<string | null>(null);

  const returnTo = (location.state as LocationState | null)?.returnTo ?? DEFAULT_DESTINATION;

  const form = useForm({
    defaultValues: { email: '', password: '', rememberMe: false },
    onSubmit: async ({ value }) => {
      setSubmitError(null);
      try {
        await login(value);
        snackbar.success('Welcome back!');
        void navigate(returnTo, { replace: true });
      } catch (error) {
        // The API's own message is the useful one here ("Email or password is
        // incorrect", "Too many failed attempts"). `getUserMessage` maps every
        // 401 to "Please sign in to continue.", which is right for an expired
        // session and useless on the form you are already signing in with.
        const normalized = normalizeError(error);
        setSubmitError(normalized.message || getUserMessage(normalized));
      }
    },
  });

  // Already signed in → skip the form and go straight to the admin area.
  if (isAuthenticated) {
    return <Navigate to={DEFAULT_DESTINATION} replace />;
  }

  const handleFormSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    event.stopPropagation();
    void form.handleSubmit();
  };

  return (
    <Box display="flex" justifyContent="center" mt={6}>
      <Paper sx={{ p: 4, width: 400 }}>
        <Typography variant="h5" gutterBottom>
          Sign in
        </Typography>

        {import.meta.env.DEV && (
          <Alert severity="info" sx={{ mb: 2 }}>
            Seeded accounts: <strong>admin@gmail.com</strong> and <strong>user@gmail.com</strong>,
            password <strong>Password123!</strong>
          </Alert>
        )}

        {/*
          `noValidate` hands validation to the schema, so the messages match the
          rest of the app instead of being the browser's own.
        */}
        <form onSubmit={handleFormSubmit} noValidate>
          <Stack spacing={2}>
            <form.Field name="email" validators={{ onBlur: emailSchema }}>
              {(field) => (
                <TextField
                  label="Email"
                  type="email"
                  // `username` is the correct autocomplete token for the
                  // identifier field even when it holds an email — password
                  // managers key off it together with current-password below.
                  autoComplete="username"
                  // A sign-in page exists to be typed into, so focusing its
                  // first field is the documented exception to this rule rather
                  // than a violation of it.
                  // eslint-disable-next-line jsx-a11y/no-autofocus
                  autoFocus
                  fullWidth
                  value={field.state.value}
                  onChange={(event: ChangeEvent<HTMLInputElement>) =>
                    field.handleChange(event.target.value)
                  }
                  onBlur={field.handleBlur}
                  error={field.state.meta.isTouched && field.state.meta.errors.length > 0}
                  helperText={
                    field.state.meta.isTouched ? fieldErrorText(field.state.meta.errors) : ' '
                  }
                />
              )}
            </form.Field>

            <form.Field name="password" validators={{ onBlur: passwordSchema }}>
              {(field) => (
                <TextField
                  label="Password"
                  type="password"
                  autoComplete="current-password"
                  fullWidth
                  value={field.state.value}
                  onChange={(event: ChangeEvent<HTMLInputElement>) =>
                    field.handleChange(event.target.value)
                  }
                  onBlur={field.handleBlur}
                  error={field.state.meta.isTouched && field.state.meta.errors.length > 0}
                  helperText={
                    field.state.meta.isTouched ? fieldErrorText(field.state.meta.errors) : ' '
                  }
                />
              )}
            </form.Field>

            <Stack direction="row" alignItems="center" justifyContent="space-between">
              <form.Field name="rememberMe">
                {(field) => (
                  <FormControlLabel
                    control={
                      <Checkbox
                        checked={field.state.value}
                        onChange={(event: ChangeEvent<HTMLInputElement>) =>
                          field.handleChange(event.target.checked)
                        }
                      />
                    }
                    label="Remember me"
                  />
                )}
              </form.Field>

              <Link component={RouterLink} to="/forgot-password" variant="body2">
                Forgot password?
              </Link>
            </Stack>

            {submitError !== null && <Alert severity="error">{submitError}</Alert>}

            <form.Subscribe selector={(state) => state.isSubmitting}>
              {(isSubmitting) => (
                <Button type="submit" variant="contained" disabled={isSubmitting} fullWidth>
                  {isSubmitting ? 'Signing in…' : 'Sign in'}
                </Button>
              )}
            </form.Subscribe>

            <Typography variant="caption" color="text.secondary">
              “Remember me” keeps you signed in for 30 days. Leave it off and the session ends when
              the browser closes.
            </Typography>
          </Stack>
        </form>
      </Paper>
    </Box>
  );
}
