// libraries/react-components/frontend/react/src/features/admin/documentation/MarkdownView.tsx
import Box from '@mui/material/Box';
import Divider from '@mui/material/Divider';
import Link from '@mui/material/Link';
import Paper from '@mui/material/Paper';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Typography from '@mui/material/Typography';
import { Fragment, memo } from 'react';

import type { BlockNode, InlineNode, ParsedMarkdown } from './markdown';

/**
 * Renders a parsed document.
 *
 * Every node becomes a React element and every string goes through a text child,
 * so **no HTML is ever constructed or injected**. There is no
 * `dangerouslySetInnerHTML` here and there must not be one — that is what makes
 * the viewer safe without a sanitizer.
 */

const HEADING_VARIANTS = ['h4', 'h5', 'h6', 'subtitle1', 'subtitle2', 'body1'] as const;

function Inline({ nodes }: { nodes: readonly InlineNode[] }) {
  return (
    <>
      {nodes.map((node, index) => {
        switch (node.kind) {
          case 'text':
            return <Fragment key={index}>{node.value}</Fragment>;
          case 'code':
            return (
              <Box
                key={index}
                component="code"
                sx={{
                  px: 0.6,
                  py: 0.2,
                  borderRadius: 0.75,
                  bgcolor: 'action.hover',
                  fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
                  fontSize: '0.86em',
                  overflowWrap: 'anywhere',
                }}
              >
                {node.value}
              </Box>
            );
          case 'strong':
            return (
              <Box key={index} component="strong" sx={{ fontWeight: 700 }}>
                <Inline nodes={node.children} />
              </Box>
            );
          case 'em':
            return (
              <Box key={index} component="em">
                <Inline nodes={node.children} />
              </Box>
            );
          case 'link': {
            // Only http(s) and in-page anchors are linkable. Anything else —
            // including a relative path to a source file — renders as text,
            // because it would 404 and because `javascript:` must never survive.
            const isSafe = /^(https?:\/\/|#)/i.test(node.href);
            if (!isSafe) {
              return (
                <Box key={index} component="span" sx={{ textDecoration: 'underline dotted' }}>
                  <Inline nodes={node.children} />
                </Box>
              );
            }
            return (
              <Link
                key={index}
                href={node.href}
                target={node.href.startsWith('#') ? undefined : '_blank'}
                rel="noopener noreferrer"
              >
                <Inline nodes={node.children} />
              </Link>
            );
          }
        }
      })}
    </>
  );
}

function Block({ node }: { node: BlockNode }) {
  switch (node.kind) {
    case 'heading':
      return (
        <Typography
          id={node.id}
          // The variant sets the *size* — a document's `#` should not render at
          // page-title scale inside a pane. `component` keeps the *element*
          // matching the source level, so the heading outline a screen reader
          // announces is the one the Markdown describes.
          variant={HEADING_VARIANTS[node.level - 1]}
          component={`h${String(node.level)}` as 'h1'}
          sx={{ fontWeight: 700, mt: node.level <= 2 ? 4 : 3, mb: 1, scrollMarginTop: 80 }}
        >
          <Inline nodes={node.children} />
        </Typography>
      );

    case 'paragraph':
      return (
        <Typography variant="body2" sx={{ mb: 1.5, lineHeight: 1.75 }}>
          <Inline nodes={node.children} />
        </Typography>
      );

    case 'code':
      return (
        <Box
          component="pre"
          sx={{
            my: 2,
            p: 2,
            borderRadius: 1.5,
            bgcolor: 'action.hover',
            border: 1,
            borderColor: 'divider',
            fontSize: 13,
            lineHeight: 1.65,
            // Code blocks are wide; they scroll inside their own box so the
            // page never scrolls sideways.
            overflowX: 'auto',
          }}
        >
          <Box component="code" aria-label={node.language ? `${node.language} code` : 'code'}>
            {node.value}
          </Box>
        </Box>
      );

    case 'list':
      return (
        <Box component={node.ordered ? 'ol' : 'ul'} sx={{ my: 1.5, pl: 3, '& li': { mb: 0.75 } }}>
          {node.items.map((item, index) => (
            <Typography key={index} component="li" variant="body2" sx={{ lineHeight: 1.7 }}>
              <Inline nodes={item} />
            </Typography>
          ))}
        </Box>
      );

    case 'table':
      return (
        <TableContainer component={Paper} variant="outlined" sx={{ my: 2 }}>
          <Table size="small">
            <TableHead>
              <TableRow>
                {node.head.map((cell, index) => (
                  <TableCell key={index} sx={{ fontWeight: 700, whiteSpace: 'nowrap' }}>
                    <Inline nodes={cell} />
                  </TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {node.rows.map((row, rowIndex) => (
                <TableRow key={rowIndex} hover>
                  {row.map((cell, cellIndex) => (
                    <TableCell key={cellIndex} sx={{ verticalAlign: 'top' }}>
                      <Inline nodes={cell} />
                    </TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      );

    case 'quote':
      return (
        <Box
          sx={{
            my: 2,
            pl: 2,
            py: 1,
            borderLeft: 4,
            borderColor: 'primary.main',
            bgcolor: 'action.hover',
            borderRadius: '0 6px 6px 0',
          }}
        >
          <Typography variant="body2" sx={{ lineHeight: 1.7 }}>
            <Inline nodes={node.children} />
          </Typography>
        </Box>
      );

    case 'rule':
      return <Divider sx={{ my: 3 }} />;
  }
}

/**
 * Memoized on the parsed document. The viewer re-renders whenever the tree's
 * open folders change, and re-rendering a 300-block document for that would be
 * wasted work.
 */
export const MarkdownView = memo(function MarkdownView({ doc }: { doc: ParsedMarkdown }) {
  return (
    <Box sx={{ maxWidth: 900 }}>
      {doc.blocks.map((block, index) => (
        <Block key={index} node={block} />
      ))}
    </Box>
  );
});

// libraries/react-components/frontend/angular/src/app/features/documentation/markdown-view.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

import type { InlineNode, ParsedMarkdown } from './markdown';

/**
 * Renders a parsed document.
 *
 * Every node becomes a real element and every string goes through an
 * interpolation, so **no HTML is ever constructed or injected**. There is no
 * `[innerHTML]` here and there must not be one — that is what makes the viewer
 * safe without a sanitizer, and why `DomSanitizer` is not imported.
 */
@Component({
  selector: 'app-markdown-inline',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @for (node of nodes(); track $index) {
      @switch (node.kind) {
        @case ('text') {
          <!--
            The interpolation is the span's entire content, with no newline
            beside it. Written bare inside the block, the indentation would join
            the same text node and collapse to a real space — enough to render
            "Error ;" where the source ends an inline-code span with a
            semicolon. (No backticks in this comment: one would terminate the
            template literal this template lives in.)
          -->
          <span>{{ $any(node).value }}</span>
        }
        @case ('code') {
          <code class="md-inline-code">{{ $any(node).value }}</code>
        }
        @case ('strong') {
          <strong><app-markdown-inline [nodes]="$any(node).children" /></strong>
        }
        @case ('em') {
          <em><app-markdown-inline [nodes]="$any(node).children" /></em>
        }
        @case ('link') {
          <!--
            Only http(s) and in-page anchors are linkable. Anything else —
            including a relative path to a source file — renders as text,
            because it would 404 and because "javascript:" must never survive.
          -->
          @if (isSafeHref($any(node).href)) {
            <a
              [href]="$any(node).href"
              [attr.target]="$any(node).href.startsWith('#') ? null : '_blank'"
              rel="noopener noreferrer"
            >
              <app-markdown-inline [nodes]="$any(node).children" />
            </a>
          } @else {
            <span class="md-dead-link">
              <app-markdown-inline [nodes]="$any(node).children" />
            </span>
          }
        }
      }
    }
  `,
  styles: `
    :host { display: inline; }
    .md-inline-code {
      padding: 1px 5px;
      border-radius: 4px;
      background: var(--mat-sys-surface-container-highest);
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
      font-size: 0.86em;
      overflow-wrap: anywhere;
    }
    .md-dead-link { text-decoration: underline dotted; }
    a { color: var(--mat-sys-primary); }
  `,
})
export class MarkdownInline {
  readonly nodes = input.required<readonly InlineNode[]>();

  protected isSafeHref(href: string): boolean {
    return /^(https?:\/\/|#)/i.test(href);
  }
}

@Component({
  selector: 'app-markdown-view',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MarkdownInline],
  template: `
    <article class="md">
      @for (block of doc().blocks; track $index) {
        @switch (block.kind) {
          @case ('heading') {
            <!-- The level is data, so the tag is chosen rather than templated. -->
            @switch ($any(block).level) {
              @case (1) { <h1 [id]="$any(block).id"><app-markdown-inline [nodes]="$any(block).children" /></h1> }
              @case (2) { <h2 [id]="$any(block).id"><app-markdown-inline [nodes]="$any(block).children" /></h2> }
              @case (3) { <h3 [id]="$any(block).id"><app-markdown-inline [nodes]="$any(block).children" /></h3> }
              @default  { <h4 [id]="$any(block).id"><app-markdown-inline [nodes]="$any(block).children" /></h4> }
            }
          }
          @case ('paragraph') {
            <p><app-markdown-inline [nodes]="$any(block).children" /></p>
          }
          @case ('code') {
            <pre class="md-code"><code [attr.aria-label]="$any(block).language ? $any(block).language + ' code' : 'code'">{{ $any(block).value }}</code></pre>
          }
          @case ('list') {
            @if ($any(block).ordered) {
              <ol>
                @for (item of $any(block).items; track $index) {
                  <li><app-markdown-inline [nodes]="item" /></li>
                }
              </ol>
            } @else {
              <ul>
                @for (item of $any(block).items; track $index) {
                  <li><app-markdown-inline [nodes]="item" /></li>
                }
              </ul>
            }
          }
          @case ('table') {
            <div class="md-table-scroll">
              <table class="md-table">
                <thead>
                  <tr>
                    @for (cell of $any(block).head; track $index) {
                      <th scope="col"><app-markdown-inline [nodes]="cell" /></th>
                    }
                  </tr>
                </thead>
                <tbody>
                  @for (row of $any(block).rows; track $index) {
                    <tr>
                      @for (cell of row; track $index) {
                        <td><app-markdown-inline [nodes]="cell" /></td>
                      }
                    </tr>
                  }
                </tbody>
              </table>
            </div>
          }
          @case ('quote') {
            <blockquote><app-markdown-inline [nodes]="$any(block).children" /></blockquote>
          }
          @case ('rule') {
            <hr />
          }
        }
      }
    </article>
  `,
  styles: `
    :host { display: block; }
    .md { max-width: 900px; }
    .md h1, .md h2, .md h3, .md h4 { font-weight: 700; margin: 32px 0 8px; scroll-margin-top: 80px; }
    .md h1 { font: var(--mat-sys-headline-medium); font-weight: 700; margin-top: 0; }
    .md h2 { font: var(--mat-sys-headline-small); font-weight: 700; }
    .md h3 { font: var(--mat-sys-title-medium); font-weight: 700; margin-top: 24px; }
    .md h4 { font: var(--mat-sys-title-small); font-weight: 700; margin-top: 20px; }
    .md p { margin: 0 0 12px; line-height: 1.75; font: var(--mat-sys-body-medium); }
    .md ul, .md ol { margin: 12px 0; padding-left: 24px; }
    .md li { margin-bottom: 6px; line-height: 1.7; font: var(--mat-sys-body-medium); }
    .md hr { border: 0; border-top: 1px solid var(--mat-sys-outline-variant); margin: 24px 0; }

    /* Code blocks are wide; they scroll inside their own box so the page
       never scrolls sideways. */
    .md-code {
      margin: 16px 0;
      padding: 16px;
      border: 1px solid var(--mat-sys-outline-variant);
      border-radius: 12px;
      background: var(--mat-sys-surface-container-highest);
      font-size: 13px;
      line-height: 1.65;
      overflow-x: auto;
    }
    .md-table-scroll { overflow-x: auto; margin: 16px 0; }
    .md-table { width: 100%; border-collapse: collapse; font: var(--mat-sys-body-small); }
    .md-table th, .md-table td {
      padding: 8px 12px;
      border: 1px solid var(--mat-sys-outline-variant);
      text-align: left;
      vertical-align: top;
    }
    .md-table th { background: var(--mat-sys-surface-container); font-weight: 700; white-space: nowrap; }
    blockquote {
      margin: 16px 0;
      padding: 8px 16px;
      border-left: 4px solid var(--mat-sys-primary);
      background: var(--mat-sys-surface-container-highest);
      border-radius: 0 8px 8px 0;
    }
    blockquote p { margin: 0; }
  `,
})
export class MarkdownView {
  readonly doc = input.required<ParsedMarkdown>();
}
