// libraries/archive/react-components/frontend/react/src/features/admin/documentation/SpecDocPage.tsx
import { SpecDocBrowser } from './SpecDocBrowser';

/** Specifications for this React app's own components. */
export function SpecDocPage() {
  return (
    <SpecDocBrowser
      setId="ui"
      title="Spec Doc"
      description="Component specifications for this React application, generated from frontend/react/specDoc."
    />
  );
}

// libraries/react-components/frontend/angular/src/app/features/documentation/spec-doc-page.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { SpecDocBrowser } from './spec-doc-browser';

/** Documentation → Spec Doc: this app's own component specifications. */
@Component({
  selector: 'app-spec-doc-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SpecDocBrowser],
  template: `
    <app-spec-doc-browser
      setId="ui"
      title="Spec Doc"
      description="Component specifications for this Angular app, generated from frontend/angular/specDoc."
    />
  `,
})
export class SpecDocPage {}
