// libraries/react-components/frontend/angular/src/app/shared/grid/editing/number-cell-editor.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { InlineEditBase } from './inline-edit-base';
import { InlineEditorShell } from './inline-editor-shell';

import type { EditorType } from './editing.types';

/** In-cell numeric editor with declarative range validation. */
@Component({
  selector: 'app-number-cell-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [InlineEditorShell],
  template: `
    <app-inline-editor-shell
      [error]="errorText()"
      [saving]="saving()"
      [canApply]="canApply()"
      (apply)="apply()"
      (cancelled)="cancel()"
    >
      <input
        #field
        class="cell-input"
        type="number"
        [value]="draft()"
        [attr.min]="params.validation?.min"
        [attr.max]="params.validation?.max"
        [attr.aria-invalid]="validationError() !== null"
        [attr.aria-label]="params.column.getColDef().headerName ?? 'Value'"
        (input)="updateDraft($any($event.target).value)"
        (keydown)="onKeydown($event)"
      />
    </app-inline-editor-shell>
  `,
  styles: `
    .cell-input {
      width: 100%;
      border: 0;
      background: transparent;
      color: inherit;
      font: inherit;
      font-size: 0.875rem;
      outline: none;
    }
  `,
})
export class NumberCellEditor<TData> extends InlineEditBase<TData, number> {
  protected readonly editorType: EditorType = 'number';

  /** Commits a number, not the string the input produced. */
  protected override parseDraft(draft: string): unknown {
    return Number(draft);
  }
}

// libraries/archive/react-components/frontend/react/src/components/grid/editing/NumberCellEditor.tsx
import TextField from '@mui/material/TextField';
import { memo } from 'react';

import { useAutoFocus } from '@/hooks/useAutoFocus';

import { InlineEditorShell } from './InlineEditorShell';
import { useInlineEdit, type InlineEditorProps } from './useInlineEdit';

/** Digits with optional leading minus and one decimal point. */
const NUMERIC_PATTERN = /^-?\d*\.?\d*$/;

/**
 * In-cell numeric editor: invalid characters are rejected at the keystroke
 * level, range rules come from `validation: { required, min, max }`, and the
 * value commits as a real `number` (via parseDraft).
 */
export const NumberCellEditor = memo(function NumberCellEditor<TData>(
  props: InlineEditorProps<TData, number>,
) {
  const edit = useInlineEdit({
    props,
    editorType: 'number',
    parseDraft: (draft) => Number(draft.trim()),
  });
  const focusRef = useAutoFocus<HTMLInputElement>();

  return (
    <InlineEditorShell
      error={edit.saveError ?? edit.validationError}
      saving={edit.saving}
      canApply={edit.canApply}
      onApply={edit.apply}
      onCancel={edit.cancel}
    >
      <TextField
        inputRef={focusRef}
        fullWidth
        variant="standard"
        type="number"
        inputMode="decimal"
        placeholder={props.column.getColDef().headerName}
        value={edit.draft}
        error={edit.validationError !== null}
        onChange={(event) => {
          // Hard-reject non-numeric characters instead of validating later.
          if (NUMERIC_PATTERN.test(event.target.value)) edit.updateDraft(event.target.value);
        }}
        slotProps={{
          htmlInput: {
            min: props.validation?.min,
            max: props.validation?.max,
            step: 'any',
          },
        }}
        sx={{ '& .MuiInput-root': { fontSize: '0.875rem' } }}
      />
    </InlineEditorShell>
  );
});
