// libraries/archive/react-components/frontend/react/src/components/grid/editing/TextCellEditor.tsx
import TextField from '@mui/material/TextField';
import { memo } from 'react';

import { useAutoFocus } from '@/hooks/useAutoFocus';

import { InlineEditorShell } from './InlineEditorShell';
import { useInlineEdit, type InlineEditorProps } from './useInlineEdit';

/**
 * In-cell text editor with declarative length validation
 * (`validation: { required, minLength, maxLength }`).
 */
export const TextCellEditor = memo(function TextCellEditor<TData>(
  props: InlineEditorProps<TData, string>,
) {
  const edit = useInlineEdit({ props, editorType: 'text' });
  const focusRef = useAutoFocus<HTMLInputElement>();

  return (
    <InlineEditorShell
      error={edit.saveError ?? edit.validationError}
      saving={edit.saving}
      canApply={edit.canApply}
      onApply={edit.apply}
      onCancel={edit.cancel}
    >
      <TextField
        inputRef={focusRef}
        fullWidth
        variant="standard"
        placeholder={props.column.getColDef().headerName}
        value={edit.draft}
        error={edit.validationError !== null}
        onChange={(event) => edit.updateDraft(event.target.value)}
        sx={{ '& .MuiInput-root': { fontSize: '0.875rem' } }}
      />
    </InlineEditorShell>
  );
});

// libraries/archive/react-components/frontend/angular/src/app/shared/grid/editing/text-cell-editor.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { InlineEditBase } from './inline-edit-base';
import { InlineEditorShell } from './inline-editor-shell';

import type { EditorType } from './editing.types';

/** In-cell text editor with declarative length validation. */
@Component({
  selector: 'app-text-cell-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [InlineEditorShell],
  template: `
    <app-inline-editor-shell
      [error]="errorText()"
      [saving]="saving()"
      [canApply]="canApply()"
      (apply)="apply()"
      (cancelled)="cancel()"
    >
      <input
        #field
        class="cell-input"
        type="text"
        [value]="draft()"
        [attr.aria-invalid]="validationError() !== null"
        [attr.aria-label]="params.column.getColDef().headerName ?? 'Value'"
        (input)="updateDraft($any($event.target).value)"
        (keydown)="onKeydown($event)"
      />
    </app-inline-editor-shell>
  `,
  styles: `
    .cell-input {
      width: 100%;
      border: 0;
      background: transparent;
      color: inherit;
      font: inherit;
      font-size: 0.875rem;
      outline: none;
    }
  `,
})
export class TextCellEditor<TData> extends InlineEditBase<TData, string> {
  protected readonly editorType: EditorType = 'text';
}
